from typing import Any, Callable


class _DemoStudentProfileSpecBuilder:
    def __init__(self, date_for: Callable[[int], str]):
        self._date = date_for

    def build(
        self,
        program_ids: dict[str, str],
        rank_ids: dict[str, str],
    ) -> list[dict[str, Any]]:
        student_specs = [
            {
                "key": "aiko",
                "first": "Aiko",
                "last": "Tanaka",
                "preferred": "Aiko",
                "dob": "2015-03-12",
                "email": None,
                "phone": None,
                "status": "active",
                "membership": self._date(-610),
                "program": program_ids["bjj_core"],
                "rank": rank_ids["white-stripe-2"],
                "tags": ["youth", "competition", "demo-ready"],
                "notes": "Quietly technical; ready to show promotion eligibility.",
                "guardian": ("Kenji", "Tanaka", "kenji.tanaka@example.test", "(555) 234-5678", "Father"),
            },
            {
                "key": "mateo",
                "first": "Mateo",
                "last": "Cruz",
                "preferred": "Mateo",
                "dob": "2013-06-04",
                "email": None,
                "phone": None,
                "status": "active",
                "membership": self._date(-420),
                "program": program_ids["bjj_core"],
                "rank": rank_ids["white-stripe-3"],
                "tags": ["youth", "leadership"],
                "notes": "Consistent attendance; next promotion requires instructor approval.",
                "guardian": ("Elena", "Cruz", "elena.cruz@example.test", "(555) 238-1199", "Mother"),
            },
            {
                "key": "priya",
                "first": "Priya",
                "last": "Sharma",
                "preferred": "Priya",
                "dob": "2010-09-18",
                "email": None,
                "phone": None,
                "status": "active",
                "membership": self._date(-300),
                "program": program_ids["bjj_core"],
                "rank": rank_ids["white"],
                "tags": ["youth", "attendance-watch"],
                "notes": "Classes are on track; needs a little more time at rank.",
                "guardian": ("Raj", "Sharma", "raj.sharma@example.test", "(555) 567-8901", "Father"),
            },
            {
                "key": "nina",
                "first": "Nina",
                "last": "Patel",
                "preferred": "Nina",
                "dob": "2011-01-21",
                "email": None,
                "phone": None,
                "status": "active",
                "membership": self._date(-150),
                "program": program_ids["bjj_core"],
                "rank": rank_ids["white-stripe-1"],
                "tags": ["youth", "new-family"],
                "notes": "Newer student with a few classes toward the next stripe.",
                "guardian": ("Anika", "Patel", "anika.patel@example.test", "(555) 410-2209", "Mother"),
            },
            {
                "key": "marcus",
                "first": "Marcus",
                "last": "Webb",
                "preferred": "Marc",
                "dob": "1992-07-22",
                "email": "marcus.webb@example.test",
                "phone": "(555) 876-5432",
                "status": "active",
                "membership": self._date(-910),
                "program": program_ids["bjj_core"],
                "rank": rank_ids["yellow"],
                "tags": ["adult", "competitor"],
                "notes": "Competition team regular; good profile for attendance history.",
                "guardian": None,
            },
            {
                "key": "sofia",
                "first": "Sofia",
                "last": "Reyes",
                "preferred": None,
                "dob": "2012-11-30",
                "email": None,
                "phone": None,
                "status": "trialing",
                "membership": self._date(-9),
                "program": program_ids["tae_kwon_do"],
                "rank": rank_ids["tkd-white"],
                "tags": ["trial", "tae-kwon-do"],
                "notes": "Trial family from the spring open house.",
                "guardian": ("Carmen", "Reyes", "carmen.reyes@example.test", "(555) 345-6789", "Mother"),
            },
            {
                "key": "derek",
                "first": "Derek",
                "last": "Kim",
                "preferred": "Derek",
                "dob": "1988-04-05",
                "email": "derek.kim@example.test",
                "phone": "(555) 456-7890",
                "status": "inactive",
                "membership": self._date(-1200),
                "program": program_ids["bjj_core"],
                "rank": rank_ids["orange"],
                "tags": ["adult", "alumni"],
                "notes": "Moved out of town. Keep for inactive roster visibility.",
                "guardian": None,
            },
            {
                "key": "james",
                "first": "James",
                "last": "O'Brien",
                "preferred": "Jimmy",
                "dob": "1979-12-01",
                "email": "james.obrien@example.test",
                "phone": "(555) 678-9012",
                "status": "paused",
                "membership": self._date(-980),
                "program": program_ids["bjj_core"],
                "rank": rank_ids["yellow"],
                "tags": ["adult", "medical-hold"],
                "notes": "On medical hold; excluded from inactivity alerts while hold is active.",
                "guardian": None,
                "hold_start": self._date(-14),
                "hold_end": self._date(30),
            },
        ]
        student_specs.extend([
            {
                "key": "hana",
                "first": "Hana",
                "last": "Mori",
                "preferred": "Hana",
                "dob": "2016-02-08",
                "email": None,
                "phone": None,
                "status": "active",
                "membership": self._date(-260),
                "program": program_ids["bjj_core"],
                "rank": rank_ids["white-stripe-1"],
                "tags": ["youth", "beginner"],
                "notes": "Steady beginner who pairs well with newer students.",
                "guardian": ("Yumi", "Mori", "yumi.mori@example.test", "(555) 241-0101", "Mother"),
            },
            {
                "key": "liam",
                "first": "Liam",
                "last": "Johnson",
                "preferred": "Liam",
                "dob": "2014-05-19",
                "email": None,
                "phone": None,
                "status": "active",
                "membership": self._date(-95),
                "program": program_ids["bjj_core"],
                "rank": rank_ids["white"],
                "tags": ["youth", "new-family"],
                "notes": "Newer student building class consistency.",
                "guardian": ("Megan", "Johnson", "megan.johnson@example.test", "(555) 241-0102", "Mother"),
            },
            {
                "key": "ava",
                "first": "Ava",
                "last": "Martinez",
                "preferred": "Ava",
                "dob": "2013-10-02",
                "email": None,
                "phone": None,
                "status": "active",
                "membership": self._date(-390),
                "program": program_ids["bjj_core"],
                "rank": rank_ids["white-stripe-2"],
                "tags": ["youth", "attendance-strong"],
                "notes": "Consistent classes and strong retention drills.",
                "guardian": ("Rosa", "Martinez", "rosa.martinez@example.test", "(555) 241-0103", "Mother"),
            },
            {
                "key": "noah_b",
                "first": "Noah",
                "last": "Bennett",
                "preferred": "Noah",
                "dob": "2012-12-11",
                "email": None,
                "phone": None,
                "status": "active",
                "membership": self._date(-510),
                "program": program_ids["bjj_core"],
                "rank": rank_ids["white-stripe-3"],
                "tags": ["youth", "promotion-watch"],
                "notes": "Close to yellow belt once approval is complete.",
                "guardian": ("Claire", "Bennett", "claire.bennett@example.test", "(555) 241-0104", "Mother"),
            },
            {
                "key": "zara",
                "first": "Zara",
                "last": "Ali",
                "preferred": "Zara",
                "dob": "2015-07-30",
                "email": None,
                "phone": None,
                "status": "active",
                "membership": self._date(-185),
                "program": program_ids["bjj_core"],
                "rank": rank_ids["white"],
                "tags": ["youth", "confidence"],
                "notes": "Developing confidence in live drills.",
                "guardian": ("Samira", "Ali", "samira.ali@example.test", "(555) 241-0105", "Mother"),
            },
            {
                "key": "ethan",
                "first": "Ethan",
                "last": "Wong",
                "preferred": "Ethan",
                "dob": "2011-04-17",
                "email": None,
                "phone": None,
                "status": "active",
                "membership": self._date(-720),
                "program": program_ids["bjj_core"],
                "rank": rank_ids["yellow"],
                "tags": ["youth", "assistant-helper"],
                "notes": "Helps newer kids with warmups.",
                "guardian": ("Michelle", "Wong", "michelle.wong@example.test", "(555) 241-0106", "Mother"),
            },
            {
                "key": "lucas",
                "first": "Lucas",
                "last": "Grant",
                "preferred": "Lucas",
                "dob": "1990-08-03",
                "email": "lucas.grant@example.test",
                "phone": "(555) 241-0107",
                "status": "active",
                "membership": self._date(-140),
                "program": program_ids["bjj_core"],
                "rank": rank_ids["white-stripe-1"],
                "tags": ["adult", "evening"],
                "notes": "Usually attends the evening no-gi block.",
                "guardian": None,
            },
            {
                "key": "maya",
                "first": "Maya",
                "last": "Chen",
                "preferred": "Maya",
                "dob": "1986-09-27",
                "email": "maya.chen@example.test",
                "phone": "(555) 241-0108",
                "status": "active",
                "membership": self._date(-1100),
                "program": program_ids["bjj_core"],
                "rank": rank_ids["orange"],
                "tags": ["adult", "mentor"],
                "notes": "Reliable mentor for fundamentals students.",
                "guardian": None,
            },
            {
                "key": "oliver",
                "first": "Oliver",
                "last": "Stone",
                "preferred": "Ollie",
                "dob": "1998-01-06",
                "email": "oliver.stone@example.test",
                "phone": "(555) 241-0109",
                "status": "active",
                "membership": self._date(-60),
                "program": program_ids["bjj_core"],
                "rank": rank_ids["white"],
                "tags": ["adult", "trial-converted"],
                "notes": "Recently converted from a trial.",
                "guardian": None,
            },
            {
                "key": "amara",
                "first": "Amara",
                "last": "Okafor",
                "preferred": "Amara",
                "dob": "1993-03-25",
                "email": "amara.okafor@example.test",
                "phone": "(555) 241-0110",
                "status": "active",
                "membership": self._date(-1380),
                "program": program_ids["bjj_core"],
                "rank": rank_ids["green"],
                "tags": ["adult", "cross-training"],
                "notes": "Advanced BJJ student also cross-training in Tae Kwon Do.",
                "guardian": None,
                "extra_programs": [
                    {"program": program_ids["tae_kwon_do"], "rank": rank_ids["tkd-white"], "status": "active", "started_at": self._date(-45)}
                ],
            },
            {
                "key": "ben",
                "first": "Ben",
                "last": "Carter",
                "preferred": "Ben",
                "dob": "1984-11-09",
                "email": "ben.carter@example.test",
                "phone": "(555) 241-0111",
                "status": "active",
                "membership": self._date(-310),
                "program": program_ids["bjj_core"],
                "rank": rank_ids["white-stripe-2"],
                "tags": ["adult", "morning"],
                "notes": "Morning class regular.",
                "guardian": None,
            },
            {
                "key": "isabella",
                "first": "Isabella",
                "last": "Rossi",
                "preferred": "Bella",
                "dob": "2014-03-14",
                "email": None,
                "phone": None,
                "status": "active",
                "membership": self._date(-235),
                "program": program_ids["bjj_core"],
                "rank": rank_ids["white-stripe-1"],
                "tags": ["youth", "after-school"],
                "notes": "After-school student with strong attendance.",
                "guardian": ("Gianna", "Rossi", "gianna.rossi@example.test", "(555) 241-0112", "Mother"),
            },
            {
                "key": "kai",
                "first": "Kai",
                "last": "Thompson",
                "preferred": "Kai",
                "dob": "2010-06-23",
                "email": None,
                "phone": None,
                "status": "active",
                "membership": self._date(-980),
                "program": program_ids["bjj_core"],
                "rank": rank_ids["orange"],
                "tags": ["youth", "competition"],
                "notes": "Competition-focused youth student.",
                "guardian": ("Andre", "Thompson", "andre.thompson@example.test", "(555) 241-0113", "Father"),
            },
            {
                "key": "mia_j",
                "first": "Mia",
                "last": "Johnson",
                "preferred": "Mia",
                "dob": "2016-09-01",
                "email": None,
                "phone": None,
                "status": "active",
                "membership": self._date(-120),
                "program": program_ids["bjj_core"],
                "rank": rank_ids["white"],
                "tags": ["youth", "new-family"],
                "notes": "Good fit for beginner fundamentals.",
                "guardian": ("Dana", "Johnson", "dana.johnson@example.test", "(555) 241-0114", "Mother"),
            },
            {
                "key": "isabel",
                "first": "Isabel",
                "last": "Torres",
                "preferred": "Izzy",
                "dob": "2012-02-28",
                "email": None,
                "phone": None,
                "status": "trialing",
                "membership": self._date(-6),
                "program": program_ids["tae_kwon_do"],
                "rank": rank_ids["tkd-white"],
                "tags": ["youth", "tae-kwon-do", "trial"],
                "notes": "Trying the youth Tae Kwon Do track.",
                "guardian": ("Marisol", "Torres", "marisol.torres@example.test", "(555) 241-0115", "Mother"),
            },
            {
                "key": "omar",
                "first": "Omar",
                "last": "Haddad",
                "preferred": "Omar",
                "dob": "1991-05-05",
                "email": "omar.haddad@example.test",
                "phone": "(555) 241-0116",
                "status": "active",
                "membership": self._date(-80),
                "program": program_ids["tae_kwon_do"],
                "rank": rank_ids["tkd-yellow"],
                "tags": ["adult", "tae-kwon-do", "cross-training"],
                "notes": "Primary Tae Kwon Do student also taking BJJ basics.",
                "guardian": None,
                "extra_programs": [
                    {"program": program_ids["bjj_core"], "rank": rank_ids["white"], "status": "active", "started_at": self._date(-25)}
                ],
            },
            {
                "key": "chloe",
                "first": "Chloe",
                "last": "Park",
                "preferred": "Chloe",
                "dob": "2013-08-20",
                "email": None,
                "phone": None,
                "status": "active",
                "membership": self._date(-130),
                "program": program_ids["tae_kwon_do"],
                "rank": rank_ids["tkd-yellow-stripe"],
                "tags": ["youth", "tae-kwon-do"],
                "notes": "Building confidence through forms and footwork drills.",
                "guardian": ("Jin", "Park", "jin.park@example.test", "(555) 241-0117", "Father"),
            },
            {
                "key": "diego",
                "first": "Diego",
                "last": "Flores",
                "preferred": "Diego",
                "dob": "1989-12-12",
                "email": "diego.flores@example.test",
                "phone": "(555) 241-0118",
                "status": "active",
                "membership": self._date(-210),
                "program": program_ids["tae_kwon_do"],
                "rank": rank_ids["tkd-yellow"],
                "tags": ["adult", "tae-kwon-do"],
                "notes": "Regular Tae Kwon Do student.",
                "guardian": None,
            },
            {
                "key": "ellie",
                "first": "Ellie",
                "last": "Smith",
                "preferred": "Ellie",
                "dob": "2015-01-16",
                "email": None,
                "phone": None,
                "status": "active",
                "membership": self._date(-70),
                "program": program_ids["tae_kwon_do"],
                "rank": rank_ids["tkd-white"],
                "tags": ["youth", "tae-kwon-do", "beginner"],
                "notes": "New beginner in the Tae Kwon Do program.",
                "guardian": ("Paula", "Smith", "paula.smith@example.test", "(555) 241-0119", "Mother"),
            },
            {
                "key": "sam",
                "first": "Sam",
                "last": "Wilson",
                "preferred": "Sam",
                "dob": "1982-07-07",
                "email": "sam.wilson@example.test",
                "phone": "(555) 241-0120",
                "status": "paused",
                "membership": self._date(-410),
                "program": program_ids["tae_kwon_do"],
                "rank": rank_ids["tkd-green-stripe"],
                "tags": ["adult", "tae-kwon-do", "travel-hold"],
                "notes": "Paused while traveling for work.",
                "guardian": None,
                "hold_start": self._date(-7),
                "hold_end": self._date(21),
            },
            {
                "key": "rebecca",
                "first": "Rebecca",
                "last": "Nguyen",
                "preferred": "Becca",
                "dob": "1987-03-09",
                "email": "rebecca.nguyen@example.test",
                "phone": "(555) 241-0121",
                "status": "active",
                "membership": self._date(-640),
                "program": program_ids["tae_kwon_do"],
                "rank": rank_ids["tkd-green"],
                "tags": ["adult", "tae-kwon-do", "promotion-watch"],
                "notes": "Adult Tae Kwon Do student ready for a blue belt review.",
                "guardian": None,
            },
            {
                "key": "miles",
                "first": "Miles",
                "last": "Brooks",
                "preferred": "Miles",
                "dob": "2014-04-04",
                "email": None,
                "phone": None,
                "status": "active",
                "membership": self._date(-340),
                "program": program_ids["tae_kwon_do"],
                "rank": rank_ids["tkd-green-stripe"],
                "tags": ["youth", "tae-kwon-do", "demo-ready"],
                "notes": "Sharp forms and a good example of Tae Kwon Do rank readiness.",
                "guardian": ("Lauren", "Brooks", "lauren.brooks@example.test", "(555) 221-0145", "Mother"),
            },
            {
                "key": "grace",
                "first": "Grace",
                "last": "Miller",
                "preferred": "Grace",
                "dob": "2015-12-02",
                "email": None,
                "phone": None,
                "status": "trialing",
                "membership": self._date(-3),
                "program": program_ids["bjj_core"],
                "rank": rank_ids["white"],
                "tags": ["trial", "needs-billing-plan"],
                "notes": "Trial student whose family needs a tuition plan decision.",
                "guardian": ("Erin", "Miller", "erin.miller@example.test", "(555) 241-0122", "Mother"),
            },
            {
                "key": "julian",
                "first": "Julian",
                "last": "Bennett",
                "preferred": "Julian",
                "dob": "2013-09-14",
                "email": None,
                "phone": None,
                "status": "active",
                "membership": self._date(-505),
                "program": program_ids["bjj_core"],
                "rank": rank_ids["white-stripe-3"],
                "tags": ["youth", "billing-attention", "promotion-watch"],
                "notes": "Ready for yellow belt review, but family has an unpaid testing invoice.",
                "guardian": ("Claire", "Bennett", "claire.bennett@example.test", "(555) 241-0104", "Mother"),
            },
        ])

        return student_specs


def build_demo_student_specs(
    *,
    date_for: Callable[[int], str],
    program_ids: dict[str, str],
    rank_ids: dict[str, str],
) -> list[dict[str, Any]]:
    return _DemoStudentProfileSpecBuilder(date_for).build(program_ids, rank_ids)
