from __future__ import annotations

from typing import Any

from app.services.report_export_catalog_types import CsvReport, _report


def build_billing_table_report_catalog(report_service_cls: Any) -> dict[str, CsvReport]:
    return {
        "billing_payers": _report(
            "billing_payers",
            "Billing payers",
            "billing-payers.csv",
            (
                "id",
                "studio_id",
                "guardian_id",
                "display_name",
                "email",
                "phone",
                "address_line1",
                "address_city",
                "address_state",
                "address_zip",
                "stripe_account_id",
                "stripe_customer_id",
                "default_payment_method_brand",
                "default_payment_method_last4",
                "autopay_status",
                "autopay_authorized_at",
                "autopay_disabled_at",
                "billing_status",
                "balance_cents",
                "metadata",
                "created_at",
                "updated_at",
            ),
            table="billing_payers",
            order_by=(("display_name", False),),
        ),
        "billing_plans": _report(
            "billing_plans",
            "Billing plans",
            "billing-plans.csv",
            (
                "id",
                "studio_id",
                "name",
                "description",
                "amount_cents",
                "currency",
                "billing_interval",
                "status",
                "signup_fee_cents",
                "trial_days",
                "proration_behavior",
                "freeze_behavior",
                "cancellation_policy",
                "tax_behavior",
                "stripe_account_id",
                "stripe_product_id",
                "stripe_price_id",
                "stripe_price_version",
                "metadata",
                "archived_at",
                "created_at",
                "updated_at",
            ),
            table="billing_plans",
            order_by=(("created_at", True),),
        ),
        "billing_plan_programs": _report(
            "billing_plan_programs",
            "Billing plan programs",
            "billing-plan-programs.csv",
            (
                "id",
                "studio_id",
                "billing_plan_id",
                "program_id",
                "created_at",
            ),
            table="billing_plan_programs",
            order_by=(("created_at", True),),
        ),
        "billing_subscriptions": _report(
            "billing_subscriptions",
            "Billing subscriptions",
            "billing-subscriptions.csv",
            (
                "id",
                "studio_id",
                "payer_id",
                "stripe_account_id",
                "stripe_customer_id",
                "stripe_subscription_id",
                "collection_mode",
                "billing_interval",
                "currency",
                "status",
                "current_period_start",
                "current_period_end",
                "cancel_at_period_end",
                "default_payment_method_id",
                "application_fee_percent",
                "metadata",
                "created_at",
                "updated_at",
            ),
            table="billing_subscriptions",
            order_by=(("created_at", True),),
        ),
        "student_billing_enrollments": _report(
            "student_billing_enrollments",
            "Student billing enrollments",
            "student-billing-enrollments.csv",
            (
                "id",
                "studio_id",
                "student_id",
                "payer_id",
                "billing_plan_id",
                "billing_subscription_id",
                "collection_mode",
                "status",
                "billing_status",
                "start_date",
                "end_date",
                "next_bill_on",
                "stripe_subscription_id",
                "stripe_subscription_item_id",
                "metadata",
                "created_at",
                "updated_at",
            ),
            table="student_billing_enrollments",
            order_by=(("created_at", True),),
        ),
        "billing_invoices": _report(
            "billing_invoices",
            "Billing invoices",
            "billing-invoices.csv",
            (
                "id",
                "studio_id",
                "payer_id",
                "student_id",
                "enrollment_id",
                "stripe_invoice_id",
                "stripe_account_id",
                "stripe_customer_id",
                "stripe_subscription_id",
                "stripe_payment_intent_id",
                "invoice_number",
                "invoice_type",
                "status",
                "amount_due_cents",
                "amount_paid_cents",
                "amount_remaining_cents",
                "currency",
                "hosted_invoice_url",
                "invoice_pdf",
                "due_date",
                "paid_at",
                "finalized_at",
                "voided_at",
                "collection_method",
                "last_payment_error",
                "application_fee_amount_cents",
                "external",
                "metadata",
                "created_at",
                "updated_at",
            ),
            table="billing_invoices",
            order_by=(("created_at", True),),
        ),
        "billing_invoice_items": _report(
            "billing_invoice_items",
            "Billing invoice items",
            "billing-invoice-items.csv",
            (
                "id",
                "studio_id",
                "invoice_id",
                "student_id",
                "enrollment_id",
                "billing_plan_id",
                "stripe_invoice_item_id",
                "stripe_price_id",
                "description",
                "quantity",
                "unit_amount_cents",
                "amount_cents",
                "metadata",
                "created_at",
            ),
            table="billing_invoice_items",
            order_by=(("created_at", True),),
        ),
        "billing_payments": _report(
            "billing_payments",
            "Billing payments",
            "billing-payments.csv",
            (
                "id",
                "studio_id",
                "payer_id",
                "invoice_id",
                "stripe_customer_id",
                "stripe_invoice_id",
                "stripe_payment_intent_id",
                "stripe_charge_id",
                "stripe_account_id",
                "stripe_payment_method_id",
                "status",
                "amount_cents",
                "currency",
                "payment_method_type",
                "external_method",
                "note",
                "receipt_url",
                "failure_code",
                "failure_message",
                "application_fee_amount_cents",
                "refunded_amount_cents",
                "processed_at",
                "metadata",
                "created_at",
                "updated_at",
            ),
            table="billing_payments",
            order_by=(("created_at", True),),
        ),
        "billing_refunds": _report(
            "billing_refunds",
            "Billing refunds",
            "billing-refunds.csv",
            (
                "id",
                "studio_id",
                "payment_id",
                "stripe_refund_id",
                "stripe_charge_id",
                "stripe_payment_intent_id",
                "stripe_account_id",
                "amount_cents",
                "status",
                "reason",
                "metadata",
                "created_at",
                "updated_at",
            ),
            table="billing_refunds",
            order_by=(("created_at", True),),
        ),
        "billing_disputes": _report(
            "billing_disputes",
            "Billing disputes",
            "billing-disputes.csv",
            (
                "id",
                "studio_id",
                "payment_id",
                "stripe_dispute_id",
                "stripe_charge_id",
                "stripe_payment_intent_id",
                "stripe_account_id",
                "amount_cents",
                "status",
                "reason",
                "liability_owner",
                "metadata",
                "created_at",
                "updated_at",
            ),
            table="billing_disputes",
            order_by=(("created_at", True),),
        ),
        "billing_adjustments": _report(
            "billing_adjustments",
            "Billing adjustments",
            "billing-adjustments.csv",
            (
                "id",
                "studio_id",
                "payer_id",
                "student_id",
                "amount_cents",
                "reason",
                "note",
                "created_by",
                "created_at",
            ),
            table="billing_adjustments",
            order_by=(("created_at", True),),
        ),
    }
