from __future__ import annotations

from typing import Any

from app.services.report_export_catalog_types import CsvReport, _report


def build_intelligence_report_catalog(report_service_cls: Any) -> dict[str, CsvReport]:
    return {
        "owner_kpi_summary": _report(
            "owner_kpi_summary",
            "Owner KPI summary",
            "owner-kpi-summary.csv",
            ("metric", "value", "context"),
            custom_builder=report_service_cls._build_owner_kpi_summary_rows,
        ),
        "quiet_churn_watchlist": _report(
            "quiet_churn_watchlist",
            "Quiet churn watchlist",
            "quiet-churn-watchlist.csv",
            (
                "student_id",
                "student_name",
                "student_status",
                "membership_start_date",
                "last_visit_date",
                "days_since_last_visit",
                "visits_last_14_days",
                "visits_last_30_days",
                "visits_previous_30_days",
                "visits_last_90_days",
                "billing_status",
                "billing_enrollment_id",
                "payer_id",
                "last_promotion_at",
                "days_since_last_promotion",
                "risk_score",
                "risk_flags",
            ),
            custom_builder=report_service_cls._build_quiet_churn_watchlist_rows,
        ),
        "first_90_days_onboarding": _report(
            "first_90_days_onboarding",
            "First 90 days onboarding",
            "first-90-days-onboarding.csv",
            (
                "student_id",
                "student_name",
                "student_status",
                "membership_start_date",
                "days_since_start",
                "first_visit_date",
                "days_to_first_visit",
                "visits_to_date",
                "visits_first_7_days",
                "visits_first_30_days",
                "visits_first_90_days",
                "completed_first_5_classes",
                "lead_source",
                "lead_id",
                "onboarding_status",
                "recommended_action",
            ),
            custom_builder=report_service_cls._build_first_90_days_onboarding_rows,
        ),
        "lead_quality_after_enrollment": _report(
            "lead_quality_after_enrollment",
            "Lead quality after enrollment",
            "lead-quality-after-enrollment.csv",
            (
                "source",
                "total_leads",
                "active_pipeline_leads",
                "enrolled_or_converted_leads",
                "lead_conversion_rate",
                "converted_students_with_records",
                "active_converted_students",
                "active_converted_student_rate",
                "first_30_day_visits",
                "avg_first_30_day_visits_per_converted_student",
                "lifetime_payment_cents",
                "avg_lifetime_payment_per_converted_student_cents",
            ),
            custom_builder=report_service_cls._build_lead_quality_after_enrollment_rows,
        ),
        "belt_momentum_testing_pipeline": _report(
            "belt_momentum_testing_pipeline",
            "Belt momentum and testing pipeline",
            "belt-momentum-testing-pipeline.csv",
            (
                "student_id",
                "student_name",
                "program_id",
                "program_name",
                "membership_id",
                "current_rank_id",
                "current_rank_name",
                "next_rank_id",
                "next_rank_name",
                "classes_since_rank_start",
                "classes_required_for_next_rank",
                "days_at_rank",
                "days_required_for_next_rank",
                "classes_met",
                "time_met",
                "requires_approval",
                "pipeline_status",
            ),
            custom_builder=report_service_cls._build_belt_momentum_testing_pipeline_rows,
        ),
        "revenue_leakage": _report(
            "revenue_leakage",
            "Revenue leakage",
            "revenue-leakage.csv",
            (
                "leakage_type",
                "severity",
                "student_id",
                "student_name",
                "payer_id",
                "payer_name",
                "enrollment_id",
                "invoice_id",
                "amount_cents",
                "detail",
                "recommended_action",
            ),
            custom_builder=report_service_cls._build_revenue_leakage_rows,
        ),
        "schedule_utilization_demand": _report(
            "schedule_utilization_demand",
            "Schedule utilization and demand",
            "schedule-utilization-demand.csv",
            (
                "program_id",
                "program_name",
                "class_name",
                "start_time",
                "sessions_scheduled",
                "sessions_canceled",
                "sessions_with_capacity",
                "total_capacity",
                "total_attendance",
                "unique_students",
                "attendance_last_30_days",
                "attendance_prior_60_days",
                "average_attendance",
                "average_capacity",
                "utilization_rate",
                "recommendation",
            ),
            custom_builder=report_service_cls._build_schedule_utilization_demand_rows,
        ),
        "family_account_health": _report(
            "family_account_health",
            "Family account health",
            "family-account-health.csv",
            (
                "household_key",
                "household_name",
                "contact_email",
                "contact_phone",
                "billing_status",
                "balance_cents",
                "total_students",
                "active_students",
                "visits_last_30_days",
                "at_risk_active_students",
                "missing_contact_method",
                "priority_score",
            ),
            custom_builder=report_service_cls._build_family_account_health_rows,
        ),
        "lifecycle_segmentation": _report(
            "lifecycle_segmentation",
            "Lifecycle segmentation",
            "lifecycle-segmentation.csv",
            (
                "student_id",
                "student_name",
                "student_status",
                "membership_start_date",
                "days_since_start",
                "lifecycle_segment",
                "segment_reason",
                "last_visit_date",
                "days_since_last_visit",
                "visits_last_30_days",
                "billing_status",
                "risk_score",
                "risk_flags",
            ),
            custom_builder=report_service_cls._build_lifecycle_segmentation_rows,
        ),
        "instructor_staff_impact": _report(
            "instructor_staff_impact",
            "Instructor and staff impact",
            "instructor-staff-impact.csv",
            (
                "staff_user_id",
                "classes_taught_90_days",
                "total_attendance_90_days",
                "average_attendance_per_class",
                "unique_students_90_days",
                "sessions_with_capacity",
                "utilization_rate",
                "assigned_leads",
                "assigned_leads_enrolled_or_converted",
                "assigned_lead_conversion_rate",
            ),
            custom_builder=report_service_cls._build_instructor_staff_impact_rows,
        ),
        "data_hygiene_readiness": _report(
            "data_hygiene_readiness",
            "Data hygiene and studio readiness",
            "data-hygiene-readiness.csv",
            (
                "issue_type",
                "severity",
                "entity_type",
                "entity_id",
                "student_id",
                "detail",
                "recommended_action",
            ),
            custom_builder=report_service_cls._build_data_hygiene_readiness_rows,
        ),
    }
