from __future__ import annotations

from typing import Any

from app.services.report_export_catalog_types import CsvReport, _report


def build_core_table_report_catalog(report_service_cls: Any) -> dict[str, CsvReport]:
    return {
        "studio_overview": _report(
            "studio_overview",
            "Studio overview",
            "studio-overview.csv",
            (
                "studio_id",
                "name",
                "slug",
                "owner_id",
                "logo_url",
                "timezone",
                "studio_created_at",
                "studio_updated_at",
                "subscription_status",
                "subscription_stripe_customer_id",
                "subscription_stripe_subscription_id",
                "subscription_plan_name",
                "subscription_monthly_price_cents",
                "subscription_currency",
                "subscription_trial_start",
                "subscription_trial_end",
                "subscription_current_period_start",
                "subscription_current_period_end",
                "subscription_cancel_at_period_end",
                "subscription_last_payment_status",
                "subscription_comped",
                "subscription_metadata",
                "payment_account_status",
                "payment_account_stripe_connected_account_id",
                "payment_account_charges_enabled",
                "payment_account_payouts_enabled",
                "payment_account_details_submitted",
                "payment_account_requirements_due",
                "payment_account_platform_fee_bps",
                "payment_account_metadata",
                "payment_account_created_at",
                "payment_account_updated_at",
            ),
            custom_builder=report_service_cls._build_studio_overview_rows,
        ),
        "students": _report(
            "students",
            "Students",
            "students.csv",
            (
                "id",
                "studio_id",
                "legal_first_name",
                "legal_last_name",
                "preferred_name",
                "date_of_birth",
                "is_minor",
                "hold_start_date",
                "hold_end_date",
                "email",
                "phone",
                "address_line1",
                "address_city",
                "address_state",
                "address_zip",
                "emergency_contact_name",
                "emergency_contact_phone",
                "emergency_contact_relation",
                "status",
                "membership_start_date",
                "program_id",
                "current_belt_rank_id",
                "stripe_customer_id",
                "photo_path",
                "photo_updated_at",
                "notes",
                "tags",
                "deleted_at",
                "created_at",
                "updated_at",
            ),
            table="students",
            order_by=(("legal_last_name", False), ("legal_first_name", False)),
        ),
        "guardian_contacts": _report(
            "guardian_contacts",
            "Guardians and contacts",
            "guardian-contacts.csv",
            (
                "student_guardian_id",
                "student_id",
                "student_legal_first_name",
                "student_legal_last_name",
                "student_preferred_name",
                "student_status",
                "student_deleted_at",
                "guardian_id",
                "guardian_first_name",
                "guardian_last_name",
                "guardian_email",
                "guardian_phone",
                "guardian_relation",
                "guardian_is_primary_contact",
                "guardian_created_at",
            ),
            custom_builder=report_service_cls._build_guardian_contact_rows,
        ),
        "student_program_memberships": _report(
            "student_program_memberships",
            "Student program enrollments",
            "student-program-enrollments.csv",
            (
                "id",
                "studio_id",
                "student_id",
                "program_id",
                "status",
                "started_at",
                "ended_at",
                "current_belt_rank_id",
                "created_at",
                "updated_at",
            ),
            table="student_program_memberships",
            order_by=(("created_at", True),),
        ),
        "programs": _report(
            "programs",
            "Programs",
            "programs.csv",
            (
                "id",
                "studio_id",
                "name",
                "description",
                "color_hex",
                "sort_order",
                "is_system",
                "archived_at",
                "created_at",
                "updated_at",
            ),
            table="programs",
            order_by=(("sort_order", False), ("name", False)),
        ),
        "belt_ladders": _report(
            "belt_ladders",
            "Belt ladders",
            "belt-ladders.csv",
            (
                "id",
                "studio_id",
                "name",
                "program_id",
                "sub_rank_term",
                "created_at",
                "updated_at",
            ),
            table="belt_ladders",
            order_by=(("created_at", False),),
        ),
        "belt_ranks": _report(
            "belt_ranks",
            "Belt ranks",
            "belt-ranks.csv",
            (
                "id",
                "ladder_id",
                "studio_id",
                "name",
                "color_hex",
                "display_order",
                "min_classes",
                "min_months",
                "requires_approval",
                "is_tip",
                "tip_color_hex",
                "created_at",
            ),
            table="belt_ranks",
            order_by=(("ladder_id", False), ("display_order", False)),
        ),
        "promotions": _report(
            "promotions",
            "Promotion history",
            "promotion-history.csv",
            (
                "id",
                "studio_id",
                "student_id",
                "student_program_membership_id",
                "program_id",
                "from_rank_id",
                "to_rank_id",
                "promoted_by",
                "notes",
                "promoted_at",
            ),
            table="promotions",
            order_by=(("promoted_at", True),),
        ),
        "leads": _report(
            "leads",
            "Leads",
            "leads.csv",
            (
                "id",
                "studio_id",
                "first_name",
                "last_name",
                "email",
                "phone",
                "source",
                "stage",
                "program_interest",
                "program_id",
                "is_minor",
                "guardian_name",
                "guardian_email",
                "guardian_phone",
                "assigned_staff_id",
                "follow_up_date",
                "lost_reason",
                "notes",
                "converted_student_id",
                "created_at",
                "updated_at",
            ),
            table="leads",
            order_by=(("created_at", True),),
        ),
        "lead_activities": _report(
            "lead_activities",
            "Lead activities",
            "lead-activities.csv",
            (
                "id",
                "studio_id",
                "lead_id",
                "activity_type",
                "description",
                "created_by",
                "created_at",
            ),
            table="lead_activities",
            order_by=(("created_at", True),),
        ),
        "class_templates": _report(
            "class_templates",
            "Recurring class templates",
            "class-templates.csv",
            (
                "id",
                "studio_id",
                "name",
                "day_of_week",
                "start_time",
                "end_time",
                "start_date",
                "end_date",
                "instructor_id",
                "program_id",
                "capacity",
                "is_active",
                "created_at",
                "updated_at",
            ),
            table="class_templates",
            order_by=(("day_of_week", False), ("start_time", False)),
        ),
        "class_sessions": _report(
            "class_sessions",
            "Class sessions",
            "class-sessions.csv",
            (
                "id",
                "studio_id",
                "template_id",
                "name",
                "date",
                "start_time",
                "end_time",
                "instructor_id",
                "program_id",
                "capacity",
                "status",
                "notes",
                "deleted_at",
                "created_at",
            ),
            table="class_sessions",
            order_by=(("date", True), ("start_time", True)),
        ),
        "attendance": _report(
            "attendance",
            "Attendance records",
            "attendance.csv",
            (
                "id",
                "studio_id",
                "session_id",
                "student_id",
                "status",
                "checked_in_at",
                "checked_in_by",
                "is_cross_program",
                "counts_toward_eligibility",
                "override_reason",
            ),
            table="attendance",
            order_by=(("checked_in_at", True),),
        ),
    }
