#!/usr/bin/env python3
from __future__ import annotations

import argparse
import importlib
import json
import re
import sys
import warnings
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
BACKEND_DIR = ROOT / "backend"
TARGET = ROOT / "frontend" / "src" / "types" / "generated" / "api-contracts.ts"

HEADER = """// AUTO-GENERATED by scripts/generate-api-types.py.
// Backend Pydantic/FastAPI OpenAPI schemas are the source of truth.
// Do not edit this file by hand; run `npm run generate:api-types`.

"""

REQUEST_SCHEMA_SUFFIXES = (
    "Create",
    "Update",
    "Request",
)
EXTRA_PYDANTIC_SCHEMA_MODELS = (
    ("app.schemas.student", "CsvImportOptions"),
    ("app.schemas.student", "CsvImportRequest"),
    ("app.schemas.student", "StudentListQueryContract"),
    ("app.schemas.schedule", "ClassSessionDeleteScope"),
)


def api_type_name(schema_name: str) -> str:
    safe_name = re.sub(r"[^A-Za-z0-9_]", "_", schema_name)
    if safe_name and safe_name[0].isdigit():
        safe_name = f"_{safe_name}"
    return f"Api{safe_name}"


def property_name(name: str) -> str:
    return name if re.fullmatch(r"[A-Za-z_$][A-Za-z0-9_$]*", name) else json.dumps(name)


def literal(value: Any) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return json.dumps(str(value))


def load_openapi() -> dict[str, Any]:
    sys.path.insert(0, str(BACKEND_DIR))
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", message="Duplicate Operation ID.*")
        from app.main import app

        return app.openapi()


def collect_ref_names(value: Any) -> set[str]:
    refs: set[str] = set()
    if isinstance(value, dict):
        ref = value.get("$ref")
        if isinstance(ref, str) and ref.startswith("#/components/schemas/"):
            refs.add(ref.rsplit("/", 1)[-1])
        for child in value.values():
            refs.update(collect_ref_names(child))
    elif isinstance(value, list):
        for item in value:
            refs.update(collect_ref_names(item))
    return refs


def expand_schema_refs(root_names: set[str], schemas: dict[str, Any]) -> set[str]:
    expanded = set(root_names)
    pending = list(root_names)
    while pending:
        schema_name = pending.pop()
        nested_refs = collect_ref_names(schemas.get(schema_name, {}))
        for ref_name in nested_refs:
            if ref_name not in expanded:
                expanded.add(ref_name)
                pending.append(ref_name)
    return expanded


def collect_response_schema_names(openapi: dict[str, Any], schemas: dict[str, Any]) -> set[str]:
    response_roots: set[str] = set()
    paths = openapi.get("paths") or {}
    for path_item in paths.values():
        if not isinstance(path_item, dict):
            continue
        for operation in path_item.values():
            if not isinstance(operation, dict):
                continue
            for response in (operation.get("responses") or {}).values():
                if not isinstance(response, dict):
                    continue
                for media in (response.get("content") or {}).values():
                    if isinstance(media, dict):
                        response_roots.update(collect_ref_names(media.get("schema")))
    return expand_schema_refs(response_roots, schemas)


def is_nullable(schema: dict[str, Any]) -> bool:
    schema_type = schema.get("type")
    if schema_type == "null":
        return True
    if isinstance(schema_type, list) and "null" in schema_type:
        return True
    return any(item.get("type") == "null" for item in schema.get("anyOf", []) + schema.get("oneOf", []))


def is_reference_like(schema: dict[str, Any]) -> bool:
    if "$ref" in schema:
        return True
    for key in ("anyOf", "oneOf", "allOf"):
        if any("$ref" in item for item in schema.get(key, [])):
            return True
    return False


def is_request_schema(schema_name: str) -> bool:
    return schema_name.startswith("Body_") or schema_name.endswith(REQUEST_SCHEMA_SUFFIXES)


def is_required_property(
    schema_name: str,
    prop_name: str,
    prop_schema: dict[str, Any],
    required: set[str],
    response_schema_names: set[str],
) -> bool:
    if prop_name in required:
        return True
    if is_request_schema(schema_name) or is_nullable(prop_schema):
        return False
    if schema_name in response_schema_names:
        return True
    return prop_schema.get("type") == "array" or is_reference_like(prop_schema)


def ref_to_type(ref: str) -> str:
    return api_type_name(ref.rsplit("/", 1)[-1])


def schema_to_ts(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return ref_to_type(schema["$ref"])

    if "allOf" in schema:
        return " & ".join(schema_to_ts(item) for item in schema["allOf"]) or "unknown"

    if "anyOf" in schema or "oneOf" in schema:
        variants = schema.get("anyOf") or schema.get("oneOf") or []
        rendered: list[str] = []
        for variant in variants:
            ts_type = schema_to_ts(variant)
            if ts_type not in rendered:
                rendered.append(ts_type)
        return " | ".join(rendered) or "unknown"

    if "enum" in schema:
        return " | ".join(literal(item) for item in schema["enum"]) or "never"

    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        non_null_types = [item for item in schema_type if item != "null"]
        rendered = [schema_to_ts({**schema, "type": item}) for item in non_null_types]
        if "null" in schema_type:
            rendered.append("null")
        return " | ".join(dict.fromkeys(rendered)) or "unknown"

    if schema_type == "string":
        return "string"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    if schema_type == "array":
        item_type = schema_to_ts(schema.get("items", {}))
        if " | " in item_type or " & " in item_type:
            item_type = f"({item_type})"
        return f"{item_type}[]"
    if schema_type == "object" or "properties" in schema:
        properties = schema.get("properties") or {}
        if properties:
            required = set(schema.get("required") or [])
            lines = ["{"]
            for prop_name, prop_schema in properties.items():
                optional = "" if prop_name in required else "?"
                lines.append(f"  {property_name(prop_name)}{optional}: {schema_to_ts(prop_schema)};")
            lines.append("}")
            return "\n".join(lines)
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            return f"Record<string, {schema_to_ts(additional)}>"
        return "Record<string, unknown>"

    return "unknown"


def render_schema(schema_name: str, schema: dict[str, Any], response_schema_names: set[str]) -> str:
    ts_name = api_type_name(schema_name)
    properties = schema.get("properties") or {}
    if schema.get("type") == "object" and properties:
        required = set(schema.get("required") or [])
        lines = [f"export interface {ts_name} {{"]
        for prop_name, prop_schema in properties.items():
            optional = "" if is_required_property(
                schema_name,
                prop_name,
                prop_schema,
                required,
                response_schema_names,
            ) else "?"
            lines.append(f"  {property_name(prop_name)}{optional}: {schema_to_ts(prop_schema)};")
        lines.append("}")
        return "\n".join(lines)

    return f"export type {ts_name} = {schema_to_ts(schema)};"


def render_contracts() -> str:
    openapi = load_openapi()
    schemas = dict(openapi.get("components", {}).get("schemas", {}))
    add_extra_pydantic_schemas(schemas)
    response_schema_names = collect_response_schema_names(openapi, schemas)
    chunks = [HEADER.rstrip()]
    for schema_name in sorted(schemas):
        chunks.append(render_schema(schema_name, schemas[schema_name], response_schema_names))
    return "\n\n".join(chunks) + "\n"


def add_extra_pydantic_schemas(schemas: dict[str, Any]) -> None:
    for module_name, model_name in EXTRA_PYDANTIC_SCHEMA_MODELS:
        module = importlib.import_module(module_name)
        model = getattr(module, model_name)
        schema = model.model_json_schema(ref_template="#/components/schemas/{model}")
        for definition_name, definition_schema in (schema.pop("$defs", {}) or {}).items():
            schemas.setdefault(definition_name, definition_schema)
        schemas.setdefault(model_name, schema)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate frontend TypeScript types from backend OpenAPI schemas.")
    parser.add_argument("--check", action="store_true", help="Fail if the generated file is out of date.")
    args = parser.parse_args()

    output = render_contracts()
    if args.check:
        existing = TARGET.read_text() if TARGET.exists() else ""
        if existing != output:
            print(
                f"{TARGET.relative_to(ROOT)} is out of date. Run `npm run generate:api-types`.",
                file=sys.stderr,
            )
            return 1
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(output)
    print(f"Wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
