import type {
  BillingInvoice,
  BillingPayment,
  BillingPlan,
  BillingPayer,
  BillingSubscription,
  PlatformBillingStatus,
  StudentBillingEnrollment,
  StudioPaymentAccount,
} from "@/types";

export const PREVIEW_BILLING_METRICS_AS_OF = new Date("2026-04-15T12:00:00Z");

export const PREVIEW_PLATFORM: PlatformBillingStatus = {
  studio_id: "mock-studio",
  plan_name: "Koaryu Core",
  monthly_price_cents: 2700,
  currency: "usd",
  status: "active",
  comped: false,
  trial_start: null,
  trial_end: null,
  current_period_start: "2026-04-01T00:00:00Z",
  current_period_end: "2026-05-01T00:00:00Z",
  cancel_at_period_end: false,
  last_payment_status: "paid",
  stripe_customer_id: "cus_demo",
  stripe_subscription_id: "sub_demo",
  email_usage: {
    included: 500,
    sent: 348,
    overage_count: 0,
    overage_rate_cents: 0.2,
    estimated_overage_cents: 0,
    period_start: "2026-04-01",
    period_end: "2026-05-01",
  },
};

export const PREVIEW_CONNECT: StudioPaymentAccount = {
  studio_id: "mock-studio",
  stripe_connected_account_id: "acct_demo",
  status: "charges_enabled",
  charges_enabled: true,
  payouts_enabled: true,
  details_submitted: true,
  requirements_due: [],
  platform_fee_bps: 50,
  liability_note: "Disputes and chargebacks on Connect direct charges remain the studio's liability.",
  created_at: "2026-03-15T12:00:00Z",
  updated_at: "2026-04-20T12:00:00Z",
};

export const PREVIEW_PLANS: BillingPlan[] = [
  {
    id: "plan-kids-unlimited",
    studio_id: "mock-studio",
    name: "Kids Unlimited",
    description: "Unlimited youth classes with belt testing billed separately.",
    amount_cents: 12900,
    currency: "usd",
    billing_interval: "monthly",
    status: "active",
    signup_fee_cents: 4900,
    trial_days: 14,
    proration_behavior: "next_cycle",
    freeze_behavior: null,
    cancellation_policy: "30 days written notice",
    tax_behavior: null,
    stripe_product_id: "prod_demo_kids",
    stripe_price_id: "price_demo_kids",
    programs: [{ program_id: "program-bjj-core", program_name: "Brazilian Jiu-Jitsu Core", program_color_hex: "#38BDF8" }],
    can_accept_payments: true,
    pending_reason: null,
    archived_at: null,
    created_at: "2026-03-15T12:00:00Z",
    updated_at: "2026-04-15T12:00:00Z",
  },
  {
    id: "plan-tkd-family",
    studio_id: "mock-studio",
    name: "Tae Kwon Do Family",
    description: "Family tuition for one or more students in Tae Kwon Do.",
    amount_cents: 17900,
    currency: "usd",
    billing_interval: "monthly",
    status: "active",
    signup_fee_cents: 0,
    trial_days: 0,
    proration_behavior: "next_cycle",
    freeze_behavior: "pause next invoice while student is on hold",
    cancellation_policy: "Month to month",
    tax_behavior: null,
    stripe_product_id: "prod_demo_tkd",
    stripe_price_id: "price_demo_tkd",
    programs: [{ program_id: "program-tae-kwon-do", program_name: "Tae Kwon Do Fundamentals", program_color_hex: "#F59E0B" }],
    can_accept_payments: true,
    pending_reason: null,
    archived_at: null,
    created_at: "2026-03-20T12:00:00Z",
    updated_at: "2026-04-15T12:00:00Z",
  },
  {
    id: "plan-testing-fees",
    studio_id: "mock-studio",
    name: "Belt Testing Fee",
    description: "One-time exam charge collected when a promotion is approved.",
    amount_cents: 3500,
    currency: "usd",
    billing_interval: "paid_in_full",
    status: "active",
    signup_fee_cents: 0,
    trial_days: 0,
    proration_behavior: "none",
    freeze_behavior: null,
    cancellation_policy: null,
    tax_behavior: null,
    stripe_product_id: "prod_demo_test",
    stripe_price_id: "price_demo_test",
    programs: [
      { program_id: "program-bjj-core", program_name: "Brazilian Jiu-Jitsu Core", program_color_hex: "#38BDF8" },
      { program_id: "program-tae-kwon-do", program_name: "Tae Kwon Do Fundamentals", program_color_hex: "#F59E0B" },
    ],
    can_accept_payments: true,
    pending_reason: null,
    archived_at: null,
    created_at: "2026-04-01T12:00:00Z",
    updated_at: "2026-04-15T12:00:00Z",
  },
];

export const PREVIEW_PAYERS: BillingPayer[] = [
  {
    id: "payer-tanaka",
    studio_id: "mock-studio",
    guardian_id: "g-1",
    display_name: "Kenji Tanaka",
    email: "kenji.tanaka@email.com",
    phone: "(555) 234-5678",
    address_line1: null,
    address_city: null,
    address_state: null,
    address_zip: null,
    stripe_customer_id: "cus_tanaka",
    stripe_payment_method_id: "pm_tanaka",
    stripe_payment_method_type: "card",
    stripe_payment_method_last4: "4242",
    stripe_payment_method_brand: "visa",
    autopay_status: "enabled",
    billing_status: "current",
    balance_cents: 0,
    created_at: "2026-03-10T12:00:00Z",
    updated_at: "2026-04-22T12:00:00Z",
  },
  {
    id: "payer-park",
    studio_id: "mock-studio",
    guardian_id: null,
    display_name: "Mina Park",
    email: "mina.park@email.com",
    phone: "(555) 987-1122",
    address_line1: null,
    address_city: null,
    address_state: null,
    address_zip: null,
    stripe_customer_id: "cus_park",
    stripe_payment_method_id: "pm_park",
    stripe_payment_method_type: "card",
    stripe_payment_method_last4: "0341",
    stripe_payment_method_brand: "mastercard",
    autopay_status: "enabled",
    billing_status: "past_due",
    balance_cents: 12900,
    created_at: "2026-03-14T12:00:00Z",
    updated_at: "2026-04-22T12:00:00Z",
  },
  {
    id: "payer-external",
    studio_id: "mock-studio",
    guardian_id: null,
    display_name: "Omar Haddad",
    email: "omar.haddad@email.com",
    phone: "(555) 222-1818",
    address_line1: null,
    address_city: null,
    address_state: null,
    address_zip: null,
    stripe_customer_id: null,
    stripe_payment_method_id: null,
    stripe_payment_method_type: null,
    stripe_payment_method_last4: null,
    stripe_payment_method_brand: null,
    autopay_status: "not_configured",
    billing_status: "externally_paid",
    balance_cents: 0,
    created_at: "2026-03-21T12:00:00Z",
    updated_at: "2026-04-20T12:00:00Z",
  },
];

export const PREVIEW_SUBSCRIPTIONS: BillingSubscription[] = [
  {
    id: "sub-local-tanaka",
    studio_id: "mock-studio",
    payer_id: "payer-tanaka",
    stripe_subscription_id: "sub_demo_tanaka",
    status: "active",
    collection_mode: "autopay",
    billing_interval: "monthly",
    currency: "usd",
    current_period_start: "2026-04-01",
    current_period_end: "2026-05-01",
    next_bill_date: "2026-05-01",
    cancel_at_period_end: false,
    created_at: "2026-03-10T12:00:00Z",
    updated_at: "2026-04-22T12:00:00Z",
  },
  {
    id: "sub-local-park",
    studio_id: "mock-studio",
    payer_id: "payer-park",
    stripe_subscription_id: "sub_demo_park",
    status: "past_due",
    collection_mode: "invoice_link",
    billing_interval: "monthly",
    currency: "usd",
    current_period_start: "2026-04-01",
    current_period_end: "2026-05-01",
    next_bill_date: "2026-05-01",
    cancel_at_period_end: false,
    created_at: "2026-03-14T12:00:00Z",
    updated_at: "2026-04-22T12:00:00Z",
  },
];

export const PREVIEW_ENROLLMENTS: StudentBillingEnrollment[] = [
  {
    id: "enroll-akira",
    studio_id: "mock-studio",
    student_id: "student-akira",
    payer_id: "payer-tanaka",
    billing_plan_id: "plan-kids-unlimited",
    plan_id: "plan-kids-unlimited",
    billing_subscription_id: "sub-local-tanaka",
    subscription_id: "sub-local-tanaka",
    stripe_subscription_id: "sub_demo_tanaka",
    stripe_subscription_item_id: "si_demo_tanaka",
    billing_status: "current",
    collection_mode: "autopay",
    status: "active",
    start_date: "2026-04-01",
    end_date: null,
    next_bill_on: "2026-05-01",
    next_bill_date: "2026-05-01",
    created_at: "2026-03-10T12:00:00Z",
    updated_at: "2026-04-22T12:00:00Z",
  },
  {
    id: "enroll-jun",
    studio_id: "mock-studio",
    student_id: "student-jun",
    payer_id: "payer-park",
    billing_plan_id: "plan-kids-unlimited",
    plan_id: "plan-kids-unlimited",
    billing_subscription_id: "sub-local-park",
    subscription_id: "sub-local-park",
    stripe_subscription_id: "sub_demo_park",
    stripe_subscription_item_id: "si_demo_park",
    billing_status: "past_due",
    collection_mode: "invoice_link",
    status: "active",
    start_date: "2026-04-01",
    end_date: null,
    next_bill_on: "2026-05-01",
    next_bill_date: "2026-05-01",
    created_at: "2026-03-14T12:00:00Z",
    updated_at: "2026-04-22T12:00:00Z",
  },
  {
    id: "enroll-omar",
    studio_id: "mock-studio",
    student_id: "student-omar",
    payer_id: "payer-external",
    billing_plan_id: "plan-tkd-family",
    plan_id: "plan-tkd-family",
    billing_subscription_id: null,
    subscription_id: null,
    stripe_subscription_id: null,
    stripe_subscription_item_id: null,
    billing_status: "externally_paid",
    collection_mode: "external",
    status: "active",
    start_date: "2026-04-05",
    end_date: null,
    next_bill_on: "2026-05-05",
    next_bill_date: "2026-05-05",
    created_at: "2026-03-21T12:00:00Z",
    updated_at: "2026-04-20T12:00:00Z",
  },
];

export const PREVIEW_INVOICES: BillingInvoice[] = [
  {
    id: "inv-paid-1",
    studio_id: "mock-studio",
    payer_id: "payer-tanaka",
    student_id: null,
    enrollment_id: null,
    stripe_invoice_id: "in_demo_paid",
    stripe_account_id: "acct_demo",
    invoice_type: "tuition",
    status: "paid",
    amount_due_cents: 12900,
    amount_paid_cents: 12900,
    amount_remaining_cents: 0,
    currency: "usd",
    hosted_invoice_url: "https://dashboard.stripe.com/test/invoices/in_demo_paid",
    due_date: "2026-04-01",
    paid_at: "2026-04-01T10:00:00Z",
    application_fee_amount_cents: 65,
    external: false,
    created_at: "2026-04-01T08:00:00Z",
    updated_at: "2026-04-01T10:00:00Z",
  },
  {
    id: "inv-failed-1",
    studio_id: "mock-studio",
    payer_id: "payer-park",
    student_id: null,
    enrollment_id: null,
    stripe_invoice_id: "in_demo_failed",
    stripe_account_id: "acct_demo",
    invoice_type: "tuition",
    status: "open",
    amount_due_cents: 12900,
    amount_paid_cents: 0,
    amount_remaining_cents: 12900,
    currency: "usd",
    hosted_invoice_url: "https://dashboard.stripe.com/test/invoices/in_demo_failed",
    due_date: "2026-04-01",
    paid_at: null,
    application_fee_amount_cents: 0,
    external: false,
    created_at: "2026-04-01T08:00:00Z",
    updated_at: "2026-04-03T08:00:00Z",
  },
  {
    id: "inv-external-1",
    studio_id: "mock-studio",
    payer_id: "payer-external",
    student_id: null,
    enrollment_id: null,
    stripe_invoice_id: null,
    stripe_account_id: null,
    invoice_type: "tuition",
    status: "paid",
    amount_due_cents: 17900,
    amount_paid_cents: 17900,
    amount_remaining_cents: 0,
    currency: "usd",
    hosted_invoice_url: null,
    due_date: "2026-04-05",
    paid_at: "2026-04-05T15:00:00Z",
    application_fee_amount_cents: 0,
    external: true,
    created_at: "2026-04-05T08:00:00Z",
    updated_at: "2026-04-05T15:00:00Z",
  },
];

export const PREVIEW_PAYMENTS: BillingPayment[] = [
  {
    id: "pay-card-1",
    studio_id: "mock-studio",
    payer_id: "payer-tanaka",
    invoice_id: "inv-paid-1",
    status: "succeeded",
    amount_cents: 12900,
    currency: "usd",
    payment_method_type: "card",
    external_method: null,
    note: null,
    application_fee_amount_cents: 65,
    refunded_amount_cents: 0,
    processed_at: "2026-04-01T10:00:00Z",
    created_at: "2026-04-01T10:00:00Z",
    updated_at: "2026-04-01T10:00:00Z",
  },
  {
    id: "pay-external-1",
    studio_id: "mock-studio",
    payer_id: "payer-external",
    invoice_id: "inv-external-1",
    status: "externally_recorded",
    amount_cents: 17900,
    currency: "usd",
    payment_method_type: null,
    external_method: "Zelle",
    note: "Recorded by front desk.",
    application_fee_amount_cents: 0,
    refunded_amount_cents: 0,
    processed_at: "2026-04-05T15:00:00Z",
    created_at: "2026-04-05T15:00:00Z",
    updated_at: "2026-04-05T15:00:00Z",
  },
];
