/**
 * Mock data for frontend development without a live Supabase connection.
 * Remove or replace with real API calls once credentials are in place.
 */
import type { Student, StudentListResponse, StudentProgramMembership } from "@/types";

function dateDaysFromToday(offsetDays: number): string {
  const date = new Date();
  date.setDate(date.getDate() + offsetDays);
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

function todayStr(): string {
  return dateDaysFromToday(0);
}

function isoDaysFromToday(offsetDays: number, time = "12:00:00"): string {
  return `${dateDaysFromToday(offsetDays)}T${time}Z`;
}

function dayOfWeek(offsetDays = 0): number {
  const date = new Date();
  date.setDate(date.getDate() + offsetDays);
  return date.getDay();
}

const MOCK_BASE_STUDENTS: Student[] = ([
  {
    id: "mock-1",
    studio_id: "mock-studio",
    legal_first_name: "Aiko",
    legal_last_name: "Tanaka",
    preferred_name: "Aiko",
    date_of_birth: "2015-03-12",
    is_minor: true,
    email: undefined,
    phone: undefined,
    status: "active",
    membership_start_date: dateDaysFromToday(-210),
    current_belt_rank_id: "rank-1",
    tags: ["youth", "competition"],
    guardians: [
      {
        id: "g-1",
        first_name: "Kenji",
        last_name: "Tanaka",
        email: "kenji.tanaka@email.com",
        phone: "(555) 234-5678",
        relation: "Father",
        is_primary_contact: true,
      },
    ],
    created_at: isoDaysFromToday(-210, "09:00:00"),
    updated_at: isoDaysFromToday(-1, "15:30:00"),
  },
  {
    id: "mock-2",
    studio_id: "mock-studio",
    legal_first_name: "Marcus",
    legal_last_name: "Webb",
    preferred_name: "Marc",
    date_of_birth: "1992-07-22",
    is_minor: false,
    email: "marcus.webb@email.com",
    phone: "(555) 876-5432",
    status: "active",
    membership_start_date: dateDaysFromToday(-420),
    current_belt_rank_id: "rank-1d",
    tags: ["adult", "competitor"],
    guardians: [],
    created_at: isoDaysFromToday(-420, "10:00:00"),
    updated_at: isoDaysFromToday(-2, "18:15:00"),
  },
  {
    id: "mock-3",
    studio_id: "mock-studio",
    legal_first_name: "Sofia",
    legal_last_name: "Reyes",
    preferred_name: undefined,
    date_of_birth: "2012-11-30",
    is_minor: true,
    email: undefined,
    phone: undefined,
    status: "trialing",
    membership_start_date: dateDaysFromToday(-15),
    current_belt_rank_id: "rank-1",
    tags: ["youth", "trial"],
    guardians: [
      {
        id: "g-2",
        first_name: "Carmen",
        last_name: "Reyes",
        email: "carmen.reyes@email.com",
        phone: "(555) 345-6789",
        relation: "Mother",
        is_primary_contact: true,
      },
    ],
    created_at: isoDaysFromToday(-15, "16:00:00"),
    updated_at: isoDaysFromToday(-1, "16:30:00"),
  },
  {
    id: "mock-4",
    studio_id: "mock-studio",
    legal_first_name: "Derek",
    legal_last_name: "Kim",
    preferred_name: "Derek",
    date_of_birth: "1988-04-05",
    is_minor: false,
    email: "derek.kim@email.com",
    phone: "(555) 456-7890",
    status: "inactive",
    membership_start_date: dateDaysFromToday(-600),
    current_belt_rank_id: "rank-2",
    tags: ["adult"],
    guardians: [],
    created_at: isoDaysFromToday(-600, "11:00:00"),
    updated_at: isoDaysFromToday(-45, "11:00:00"),
  },
  {
    id: "mock-5",
    studio_id: "mock-studio",
    legal_first_name: "Priya",
    legal_last_name: "Sharma",
    preferred_name: "Priya",
    date_of_birth: "2010-09-18",
    is_minor: true,
    email: undefined,
    phone: undefined,
    status: "active",
    membership_start_date: dateDaysFromToday(-260),
    current_belt_rank_id: "rank-1b",
    tags: ["youth"],
    guardians: [
      {
        id: "g-3",
        first_name: "Raj",
        last_name: "Sharma",
        email: "raj.sharma@email.com",
        phone: "(555) 567-8901",
        relation: "Father",
        is_primary_contact: true,
      },
    ],
    created_at: isoDaysFromToday(-260, "12:00:00"),
    updated_at: isoDaysFromToday(-1, "17:00:00"),
  },
  {
    id: "mock-7",
    studio_id: "mock-studio",
    legal_first_name: "Nora",
    legal_last_name: "Patel",
    preferred_name: "Nora",
    date_of_birth: "1995-05-14",
    is_minor: false,
    email: "nora.patel@email.com",
    phone: "(555) 246-8101",
    status: "active",
    membership_start_date: dateDaysFromToday(-120),
    current_belt_rank_id: "rank-2a",
    notes: "Usually attends lunch classes. Good candidate for a quick reactivation text.",
    tags: ["adult", "follow-up"],
    guardians: [],
    created_at: isoDaysFromToday(-120, "13:00:00"),
    updated_at: isoDaysFromToday(-21, "13:00:00"),
  },
  {
    id: "mock-8",
    studio_id: "mock-studio",
    legal_first_name: "Leo",
    legal_last_name: "Nguyen",
    preferred_name: "Leo",
    date_of_birth: "2017-08-09",
    is_minor: true,
    email: undefined,
    phone: undefined,
    status: "trialing",
    membership_start_date: dateDaysFromToday(-5),
    current_belt_rank_id: "rank-1",
    tags: ["youth", "trial"],
    guardians: [
      {
        id: "g-4",
        first_name: "Mai",
        last_name: "Nguyen",
        email: "mai.nguyen@email.com",
        phone: "(555) 135-7911",
        relation: "Mother",
        is_primary_contact: true,
      },
    ],
    created_at: isoDaysFromToday(-5, "14:00:00"),
    updated_at: isoDaysFromToday(-1, "09:30:00"),
  },
  {
    id: "mock-6",
    studio_id: "mock-studio",
    legal_first_name: "James",
    legal_last_name: "O'Brien",
    preferred_name: "Jimmy",
    date_of_birth: "1979-12-01",
    is_minor: false,
    email: "james.obrien@email.com",
    phone: "(555) 678-9012",
    status: "paused",
    hold_start_date: dateDaysFromToday(-10),
    hold_end_date: dateDaysFromToday(20),
    membership_start_date: dateDaysFromToday(-700),
    current_belt_rank_id: "rank-5",
    notes: "On medical hold this month. Contact before reactivating.",
    tags: ["adult", "medical-hold"],
    guardians: [],
    created_at: isoDaysFromToday(-700, "10:30:00"),
    updated_at: isoDaysFromToday(-10, "09:00:00"),
  },
]).map((student) => ({
  ...student,
  status: student.status as Student["status"],
  program_id: "program-bjj-core",
  program_memberships: [
    {
      id: `${student.id}-program-primary`,
      studio_id: student.studio_id,
      student_id: student.id,
      program_id: "program-bjj-core",
      program_name: "Brazilian Jiu-Jitsu Core",
      program_color_hex: "#38BDF8",
      status: "active",
      started_at: student.membership_start_date,
      ended_at: null,
      current_belt_rank_id: student.current_belt_rank_id ?? null,
      created_at: student.created_at,
      updated_at: student.updated_at,
    },
  ],
}));

const MOCK_ADDITIONAL_STUDENTS: Student[] = [
  ["mock-9", "Hana", "Mori", "Hana", "2016-02-08", true, "active", -260, "rank-1a", ["youth", "beginner"]],
  ["mock-10", "Liam", "Johnson", "Liam", "2014-05-19", true, "active", -95, "rank-1", ["youth", "new-family"]],
  ["mock-11", "Ava", "Martinez", "Ava", "2013-10-02", true, "active", -390, "rank-1b", ["youth", "attendance-strong"]],
  ["mock-12", "Noah", "Bennett", "Noah", "2012-12-11", true, "active", -510, "rank-1d", ["youth", "promotion-watch"]],
  ["mock-13", "Zara", "Ali", "Zara", "2015-07-30", true, "active", -185, "rank-1", ["youth", "confidence"]],
  ["mock-14", "Ethan", "Wong", "Ethan", "2011-04-17", true, "active", -720, "rank-2", ["youth", "assistant-helper"]],
  ["mock-15", "Lucas", "Grant", "Lucas", "1990-08-03", false, "active", -140, "rank-1a", ["adult", "evening"]],
  ["mock-16", "Maya", "Chen", "Maya", "1986-09-27", false, "active", -1100, "rank-4", ["adult", "mentor"]],
  ["mock-17", "Amara", "Okafor", "Amara", "1993-03-25", false, "active", -1380, "rank-6", ["adult", "cross-training"]],
  ["mock-18", "Kai", "Thompson", "Kai", "2010-06-23", true, "active", -980, "rank-4", ["youth", "competition"]],
  ["mock-19", "Omar", "Haddad", "Omar", "1991-05-05", false, "active", -80, "tkd-rank-2", ["adult", "tae-kwon-do", "cross-training"]],
  ["mock-20", "Chloe", "Park", "Chloe", "2013-08-20", true, "active", -130, "tkd-rank-1a", ["youth", "tae-kwon-do"]],
].map(([id, first, last, preferred, dob, isMinor, status, membershipOffset, rankId, tags]) => {
  const isTaeKwonDoPrimary = (tags as string[]).includes("tae-kwon-do");
  const primaryProgramId = isTaeKwonDoPrimary ? "program-tae-kwon-do" : "program-bjj-core";
  const primaryProgramName = isTaeKwonDoPrimary ? "Tae Kwon Do Fundamentals" : "Brazilian Jiu-Jitsu Core";
  const primaryProgramColor = isTaeKwonDoPrimary ? "#F59E0B" : "#38BDF8";
  const startedAt = dateDaysFromToday(membershipOffset as number);
  const studentId = id as string;
  const memberships: StudentProgramMembership[] = [
    {
      id: `${studentId}-program-primary`,
      studio_id: "mock-studio",
      student_id: studentId,
      program_id: primaryProgramId,
      program_name: primaryProgramName,
      program_color_hex: primaryProgramColor,
      status: "active" as const,
      started_at: startedAt,
      ended_at: null,
      current_belt_rank_id: (rankId as string | undefined) ?? null,
      current_belt_rank_name: isTaeKwonDoPrimary
        ? rankId === "tkd-rank-2"
          ? "Yellow Belt"
          : "Yellow Stripe"
        : null,
      current_belt_rank_color: isTaeKwonDoPrimary
        ? rankId === "tkd-rank-2"
          ? "#EAB308"
          : "#FFFFFF"
        : null,
      created_at: isoDaysFromToday(membershipOffset as number, "09:00:00"),
      updated_at: isoDaysFromToday(-1, "09:00:00"),
    },
  ];
  if (studentId === "mock-17") {
    memberships.push({
      id: `${studentId}-program-tae-kwon-do`,
      studio_id: "mock-studio",
      student_id: studentId,
      program_id: "program-tae-kwon-do",
      program_name: "Tae Kwon Do Fundamentals",
      program_color_hex: "#F59E0B",
      status: "active",
      started_at: dateDaysFromToday(-45),
      ended_at: null,
      current_belt_rank_id: "tkd-rank-1",
      current_belt_rank_name: "White Belt",
      current_belt_rank_color: "#FFFFFF",
      created_at: isoDaysFromToday(-45, "09:00:00"),
      updated_at: isoDaysFromToday(-1, "09:00:00"),
    });
  }
  if (studentId === "mock-19") {
    memberships.push({
      id: `${studentId}-program-bjj`,
      studio_id: "mock-studio",
      student_id: studentId,
      program_id: "program-bjj-core",
      program_name: "Brazilian Jiu-Jitsu Core",
      program_color_hex: "#38BDF8",
      status: "active",
      started_at: dateDaysFromToday(-25),
      ended_at: null,
      current_belt_rank_id: "rank-1",
      current_belt_rank_name: "White Belt",
      current_belt_rank_color: "#FFFFFF",
      created_at: isoDaysFromToday(-25, "09:00:00"),
      updated_at: isoDaysFromToday(-1, "09:00:00"),
    });
  }

  return {
    id: studentId,
    studio_id: "mock-studio",
    legal_first_name: first as string,
    legal_last_name: last as string,
    preferred_name: preferred as string,
    date_of_birth: dob as string,
    is_minor: isMinor as boolean,
    email: isMinor ? undefined : `${String(first).toLowerCase()}.${String(last).toLowerCase()}@email.com`,
    phone: isMinor ? undefined : "(555) 246-8000",
    status: status as Student["status"],
    membership_start_date: startedAt,
    program_id: primaryProgramId,
    current_belt_rank_id: rankId as string | undefined,
    program_memberships: memberships,
    notes: isTaeKwonDoPrimary ? "Part of the Tae Kwon Do program roster." : "Demo student for program filtering and rank readiness.",
    tags: tags as string[],
    guardians: isMinor
      ? [
          {
            id: `${studentId}-guardian`,
            first_name: "Demo",
            last_name: last as string,
            email: `guardian.${String(last).toLowerCase()}@email.com`,
            phone: "(555) 246-8001",
            relation: "Guardian",
            is_primary_contact: true,
          },
        ]
      : [],
    created_at: isoDaysFromToday(membershipOffset as number, "09:00:00"),
    updated_at: isoDaysFromToday(-1, "09:00:00"),
  };
});

export const MOCK_STUDENTS: Student[] = [...MOCK_BASE_STUDENTS, ...MOCK_ADDITIONAL_STUDENTS];

export const MOCK_STUDENT_LIST: StudentListResponse = {
  items: MOCK_STUDENTS,
  total: MOCK_STUDENTS.length,
  page: 1,
  page_size: 50,
};

// ---- Phase 3: Schedule Mock Data ----

import type {
  ClassTemplate,
  ClassSession,
  AttendanceRecord,
  BeltLadder,
  BeltRank,
  EligibilityEntry,
  Lead,
} from "@/types";

export const MOCK_CLASS_TEMPLATES: ClassTemplate[] = [
  {
    id: "tmpl-1",
    studio_id: "mock-studio",
    name: "Kids BJJ Fundamentals",
    day_of_week: dayOfWeek(),
    start_date: todayStr(),
    start_time: "16:00",
    end_time: "16:45",
    program_id: "program-bjj-core",
    capacity: 20,
    is_active: true,
    created_at: isoDaysFromToday(-90, "09:00:00"),
    updated_at: isoDaysFromToday(-2, "09:00:00"),
  },
  {
    id: "tmpl-2",
    studio_id: "mock-studio",
    name: "Adult No-Gi",
    day_of_week: dayOfWeek(),
    start_date: todayStr(),
    start_time: "18:00",
    end_time: "19:30",
    program_id: "program-bjj-core",
    capacity: 30,
    is_active: true,
    created_at: isoDaysFromToday(-90, "09:05:00"),
    updated_at: isoDaysFromToday(-2, "09:05:00"),
  },
  {
    id: "tmpl-3",
    studio_id: "mock-studio",
    name: "Open Mat",
    day_of_week: dayOfWeek(1),
    start_date: todayStr(),
    start_time: "10:00",
    end_time: "12:00",
    program_id: "program-bjj-core",
    capacity: 40,
    is_active: true,
    created_at: isoDaysFromToday(-90, "09:10:00"),
    updated_at: isoDaysFromToday(-2, "09:10:00"),
  },
  {
    id: "tmpl-4",
    studio_id: "mock-studio",
    name: "Competition Prep",
    day_of_week: dayOfWeek(2),
    start_date: todayStr(),
    start_time: "17:00",
    end_time: "18:30",
    program_id: "program-bjj-core",
    capacity: 15,
    is_active: true,
    created_at: isoDaysFromToday(-90, "09:15:00"),
    updated_at: isoDaysFromToday(-2, "09:15:00"),
  },
  {
    id: "tmpl-5",
    studio_id: "mock-studio",
    name: "Tae Kwon Do Fundamentals",
    day_of_week: dayOfWeek(1),
    start_date: todayStr(),
    start_time: "17:30",
    end_time: "18:30",
    program_id: "program-tae-kwon-do",
    capacity: 24,
    is_active: true,
    created_at: isoDaysFromToday(-90, "09:20:00"),
    updated_at: isoDaysFromToday(-2, "09:20:00"),
  },
];

export const MOCK_SESSIONS: ClassSession[] = [
  {
    id: "sess-1",
    studio_id: "mock-studio",
    template_id: "tmpl-1",
    name: "Kids BJJ Fundamentals",
    date: todayStr(),
    start_time: "16:00",
    end_time: "16:45",
    program_id: "program-bjj-core",
    capacity: 20,
    status: "scheduled",
    created_at: todayStr() + "T00:00:00Z",
    attendance_count: 3,
  },
  {
    id: "sess-2",
    studio_id: "mock-studio",
    template_id: "tmpl-2",
    name: "Adult No-Gi",
    date: todayStr(),
    start_time: "18:00",
    end_time: "19:30",
    program_id: "program-bjj-core",
    capacity: 30,
    status: "scheduled",
    created_at: todayStr() + "T00:00:00Z",
    attendance_count: 2,
  },
  {
    id: "sess-3",
    studio_id: "mock-studio",
    template_id: "tmpl-5",
    name: "Tae Kwon Do Fundamentals",
    date: todayStr(),
    start_time: "17:30",
    end_time: "18:30",
    program_id: "program-tae-kwon-do",
    capacity: 24,
    status: "scheduled",
    created_at: todayStr() + "T00:00:00Z",
    attendance_count: 2,
  },
];

export const MOCK_ATTENDANCE: AttendanceRecord[] = [
  {
    id: "att-1",
    studio_id: "mock-studio",
    session_id: "sess-1",
    student_id: "mock-1",
    status: "present",
    checked_in_at: `${todayStr()}T16:00:00Z`,
    is_cross_program: false,
    counts_toward_eligibility: true,
    student_name: "Aiko Tanaka",
  },
  {
    id: "att-2",
    studio_id: "mock-studio",
    session_id: "sess-1",
    student_id: "mock-5",
    status: "present",
    checked_in_at: `${todayStr()}T16:02:00Z`,
    is_cross_program: false,
    counts_toward_eligibility: true,
    student_name: "Priya Sharma",
  },
  {
    id: "att-3",
    studio_id: "mock-studio",
    session_id: "sess-1",
    student_id: "mock-3",
    status: "late",
    checked_in_at: `${todayStr()}T16:10:00Z`,
    is_cross_program: false,
    counts_toward_eligibility: true,
    student_name: "Sofia Reyes",
  },
  {
    id: "att-4",
    studio_id: "mock-studio",
    session_id: "sess-2",
    student_id: "mock-2",
    status: "present",
    checked_in_at: `${todayStr()}T18:01:00Z`,
    is_cross_program: false,
    counts_toward_eligibility: true,
    student_name: "Marc Webb",
  },
  {
    id: "att-5",
    studio_id: "mock-studio",
    session_id: "sess-2",
    student_id: "mock-4",
    status: "present",
    checked_in_at: `${todayStr()}T18:04:00Z`,
    is_cross_program: false,
    counts_toward_eligibility: true,
    student_name: "Derek Kim",
  },
  {
    id: "att-6",
    studio_id: "mock-studio",
    session_id: "historic-nora",
    student_id: "mock-7",
    status: "present",
    checked_in_at: `${dateDaysFromToday(-21)}T12:05:00Z`,
    is_cross_program: false,
    counts_toward_eligibility: true,
    student_name: "Nora Patel",
  },
  {
    id: "att-7",
    studio_id: "mock-studio",
    session_id: "sess-3",
    student_id: "mock-19",
    status: "present",
    checked_in_at: `${todayStr()}T17:35:00Z`,
    is_cross_program: false,
    counts_toward_eligibility: true,
    student_name: "Omar Haddad",
  },
  {
    id: "att-8",
    studio_id: "mock-studio",
    session_id: "sess-3",
    student_id: "mock-20",
    status: "present",
    checked_in_at: `${todayStr()}T17:36:00Z`,
    is_cross_program: false,
    counts_toward_eligibility: true,
    student_name: "Chloe Park",
  },
];

// ---- Phase 4: Belt Tracker Mock Data ----

export const MOCK_BELT_RANKS: BeltRank[] = [
  // ---- White Belt ----
  {
    id: "rank-1",
    ladder_id: "ladder-1",
    studio_id: "mock-studio",
    name: "White Belt",
    color_hex: "#FFFFFF",
    display_order: 0,
    min_classes: 0,
    min_months: 0,
    requires_approval: false,
    is_tip: false,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "rank-1a",
    ladder_id: "ladder-1",
    studio_id: "mock-studio",
    name: "Red Tip 1",
    color_hex: "#FFFFFF",
    tip_color_hex: "#EF4444",
    display_order: 1,
    min_classes: 8,
    min_months: 1,
    requires_approval: false,
    is_tip: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "rank-1b",
    ladder_id: "ladder-1",
    studio_id: "mock-studio",
    name: "Red Tip 2",
    color_hex: "#FFFFFF",
    tip_color_hex: "#EF4444",
    display_order: 2,
    min_classes: 8,
    min_months: 1,
    requires_approval: false,
    is_tip: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "rank-1c",
    ladder_id: "ladder-1",
    studio_id: "mock-studio",
    name: "Red Tip 3",
    color_hex: "#FFFFFF",
    tip_color_hex: "#EF4444",
    display_order: 3,
    min_classes: 8,
    min_months: 1,
    requires_approval: false,
    is_tip: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "rank-1d",
    ladder_id: "ladder-1",
    studio_id: "mock-studio",
    name: "Black Tip",
    color_hex: "#FFFFFF",
    tip_color_hex: "#111111",
    display_order: 4,
    min_classes: 10,
    min_months: 2,
    requires_approval: true,
    is_tip: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  // ---- Yellow Belt ----
  {
    id: "rank-2",
    ladder_id: "ladder-1",
    studio_id: "mock-studio",
    name: "Yellow Belt",
    color_hex: "#EAB308",
    display_order: 5,
    min_classes: 20,
    min_months: 3,
    requires_approval: true,
    is_tip: false,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "rank-2a",
    ladder_id: "ladder-1",
    studio_id: "mock-studio",
    name: "Yellow Tip",
    color_hex: "#EAB308",
    tip_color_hex: "#EAB308",
    display_order: 6,
    min_classes: 10,
    min_months: 2,
    requires_approval: false,
    is_tip: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  // ---- Orange Belt ----
  {
    id: "rank-3",
    ladder_id: "ladder-1",
    studio_id: "mock-studio",
    name: "Orange Belt",
    color_hex: "#F97316",
    display_order: 7,
    min_classes: 30,
    min_months: 6,
    requires_approval: true,
    is_tip: false,
    created_at: "2024-01-01T00:00:00Z",
  },
  // ---- Purple Belt ----
  {
    id: "rank-4",
    ladder_id: "ladder-1",
    studio_id: "mock-studio",
    name: "Purple Belt",
    color_hex: "#8B5CF6",
    display_order: 8,
    min_classes: 50,
    min_months: 12,
    requires_approval: true,
    is_tip: false,
    created_at: "2024-01-01T00:00:00Z",
  },
  // ---- Blue Belt ----
  {
    id: "rank-5",
    ladder_id: "ladder-1",
    studio_id: "mock-studio",
    name: "Blue Belt",
    color_hex: "#3B82F6",
    display_order: 9,
    min_classes: 75,
    min_months: 18,
    requires_approval: true,
    is_tip: false,
    created_at: "2024-01-01T00:00:00Z",
  },
  // ---- Green Belt ----
  {
    id: "rank-6",
    ladder_id: "ladder-1",
    studio_id: "mock-studio",
    name: "Green Belt",
    color_hex: "#22C55E",
    display_order: 10,
    min_classes: 100,
    min_months: 24,
    requires_approval: true,
    is_tip: false,
    created_at: "2024-01-01T00:00:00Z",
  },
  // ---- Brown Belt ----
  {
    id: "rank-7",
    ladder_id: "ladder-1",
    studio_id: "mock-studio",
    name: "Brown Belt",
    color_hex: "#92400E",
    display_order: 11,
    min_classes: 150,
    min_months: 36,
    requires_approval: true,
    is_tip: false,
    created_at: "2024-01-01T00:00:00Z",
  },
  // ---- Black Belt ----
  {
    id: "rank-8",
    ladder_id: "ladder-1",
    studio_id: "mock-studio",
    name: "Black Belt",
    color_hex: "#111111",
    display_order: 12,
    min_classes: 250,
    min_months: 60,
    requires_approval: true,
    is_tip: false,
    created_at: "2024-01-01T00:00:00Z",
  },
];

export const MOCK_BELT_LADDER: BeltLadder = {
  id: "ladder-1",
  studio_id: "mock-studio",
  name: "Brazilian Jiu-Jitsu Core",
  program_id: "program-bjj-core",
  sub_rank_term: "Stripe",
  created_at: "2024-01-01T00:00:00Z",
  updated_at: "2024-01-01T00:00:00Z",
  ranks: MOCK_BELT_RANKS,
};

export const MOCK_ELIGIBILITY: EligibilityEntry[] = [
  {
    student_id: "mock-1",
    student_name: "Aiko Tanaka",
    current_rank_id: "rank-1",
    current_rank_name: "White Belt",
    current_rank_color: "#FFFFFF",
    next_rank_id: "rank-1a",
    next_rank_name: "Red Tip 1",
    next_rank_color: "#FFFFFF",
    classes_since_promo: 6,
    classes_required: 8,
    days_at_rank: 25,
    days_required: 30,
    classes_met: false,
    time_met: false,
    needs_approval: false,
    is_eligible: false,
  },
  {
    student_id: "mock-5",
    student_name: "Priya Sharma",
    current_rank_id: "rank-1b",
    current_rank_name: "Red Tip 2",
    current_rank_color: "#FFFFFF",
    next_rank_id: "rank-1c",
    next_rank_name: "Red Tip 3",
    next_rank_color: "#FFFFFF",
    classes_since_promo: 9,
    classes_required: 8,
    days_at_rank: 35,
    days_required: 30,
    classes_met: true,
    time_met: true,
    needs_approval: false,
    is_eligible: true,
  },
  {
    student_id: "mock-2",
    student_name: "Marc Webb",
    current_rank_id: "rank-1d",
    current_rank_name: "Black Tip",
    current_rank_color: "#FFFFFF",
    next_rank_id: "rank-2",
    next_rank_name: "Yellow Belt",
    next_rank_color: "#EAB308",
    classes_since_promo: 12,
    classes_required: 10,
    days_at_rank: 65,
    days_required: 60,
    classes_met: true,
    time_met: true,
    needs_approval: true,
    is_eligible: false,
  },
  {
    student_id: "mock-6",
    student_name: "Jimmy O'Brien",
    current_rank_id: "rank-5",
    current_rank_name: "Blue Belt",
    current_rank_color: "#3B82F6",
    next_rank_id: "rank-6",
    next_rank_name: "Green Belt",
    next_rank_color: "#22C55E",
    classes_since_promo: 110,
    classes_required: 100,
    days_at_rank: 560,
    days_required: 548,
    classes_met: true,
    time_met: true,
    needs_approval: true,
    is_eligible: false,
  },
  {
    student_id: "mock-7",
    student_name: "Nora Patel",
    current_rank_id: "rank-2a",
    current_rank_name: "Yellow Tip",
    current_rank_color: "#EAB308",
    next_rank_id: "rank-3",
    next_rank_name: "Orange Belt",
    next_rank_color: "#F97316",
    classes_since_promo: 18,
    classes_required: 30,
    days_at_rank: 75,
    days_required: 180,
    classes_met: false,
    time_met: false,
    needs_approval: true,
    is_eligible: false,
  },
  {
    student_id: "mock-4",
    student_name: "Derek Kim",
    current_rank_id: "rank-2",
    current_rank_name: "Yellow Belt",
    current_rank_color: "#EAB308",
    next_rank_id: "rank-3",
    next_rank_name: "Orange Belt",
    next_rank_color: "#F97316",
    classes_since_promo: 22,
    classes_required: 30,
    days_at_rank: 120,
    days_required: 180,
    classes_met: false,
    time_met: false,
    needs_approval: true,
    is_eligible: false,
  },
];

// ---- Phase 5: Leads Mock Data ----


export const MOCK_LEADS: Lead[] = [
  {
    id: "lead-1",
    studio_id: "mock-studio",
    first_name: "David",
    last_name: "Chen",
    email: "david.chen@email.com",
    phone: "(555) 111-2222",
    source: "website",
    stage: "inquiry",
    program_interest: "Brazilian Jiu-Jitsu Core",
    program_id: "program-bjj-core",
    is_minor: false,
    follow_up_date: todayStr(),
    notes: "Interested in evening classes. Has prior wrestling experience.",
    created_at: isoDaysFromToday(-6, "10:00:00"),
    updated_at: isoDaysFromToday(-1, "10:00:00"),
  },
  {
    id: "lead-2",
    studio_id: "mock-studio",
    first_name: "Maria",
    last_name: "Gonzalez",
    email: "maria.g@email.com",
    phone: "(555) 333-4444",
    source: "referral",
    stage: "trial_scheduled",
    program_interest: "Brazilian Jiu-Jitsu Core",
    program_id: "program-bjj-core",
    is_minor: true,
    guardian_name: "Elena Gonzalez",
    guardian_email: "elena.g@email.com",
    guardian_phone: "(555) 333-4445",
    follow_up_date: dateDaysFromToday(1),
    notes: "Referred by Carmen Reyes. Daughter is 8 years old.",
    created_at: isoDaysFromToday(-8, "14:00:00"),
    updated_at: isoDaysFromToday(-2, "09:00:00"),
  },
  {
    id: "lead-3",
    studio_id: "mock-studio",
    first_name: "Tyler",
    last_name: "Brooks",
    email: "tyler.b@email.com",
    source: "social",
    stage: "trial_completed",
    program_interest: "Brazilian Jiu-Jitsu Core",
    program_id: "program-bjj-core",
    is_minor: false,
    follow_up_date: todayStr(),
    notes: "Completed trial class on 4/12. Very enthusiastic. Follow up with pricing.",
    created_at: isoDaysFromToday(-12, "08:00:00"),
    updated_at: isoDaysFromToday(-3, "11:00:00"),
  },
  {
    id: "lead-4",
    studio_id: "mock-studio",
    first_name: "Sarah",
    last_name: "Kim",
    email: "sarah.kim@email.com",
    phone: "(555) 555-6666",
    source: "walk_in",
    stage: "offer_sent",
    program_interest: "Brazilian Jiu-Jitsu Core",
    program_id: "program-bjj-core",
    is_minor: false,
    follow_up_date: dateDaysFromToday(-1),
    notes: "Sent Growth plan pricing. Waiting for decision.",
    created_at: isoDaysFromToday(-14, "16:00:00"),
    updated_at: isoDaysFromToday(-1, "10:00:00"),
  },
  {
    id: "lead-5",
    studio_id: "mock-studio",
    first_name: "Ryan",
    last_name: "Patel",
    email: "ryan.p@email.com",
    phone: "(555) 777-8888",
    source: "search",
    stage: "closed_lost",
    program_interest: "Tae Kwon Do Fundamentals",
    program_id: "program-tae-kwon-do",
    is_minor: false,
    lost_reason: "price_objection",
    notes: "Price was the deciding factor. May reconsider if we run a promo.",
    created_at: isoDaysFromToday(-24, "12:00:00"),
    updated_at: isoDaysFromToday(-15, "15:00:00"),
  },
];
