/**
 * Mock data for frontend development without a live Supabase connection.
 * Remove or replace with real API calls once credentials are in place.
 */
import type { Student, StudentListResponse } from "@/types";

export const MOCK_STUDENTS: Student[] = [
  {
    id: "mock-1",
    studio_id: "mock-studio",
    legal_first_name: "Aiko",
    legal_last_name: "Tanaka",
    preferred_name: "Aiko",
    date_of_birth: "2015-03-12",
    is_minor: true,
    email: undefined,
    phone: undefined,
    status: "active",
    membership_start_date: "2023-09-01",
    tags: ["youth", "competition"],
    guardians: [
      {
        id: "g-1",
        first_name: "Kenji",
        last_name: "Tanaka",
        email: "kenji.tanaka@email.com",
        phone: "(555) 234-5678",
        relation: "Father",
        is_primary_contact: true,
      },
    ],
    created_at: "2023-09-01T00:00:00Z",
    updated_at: "2024-11-15T00:00:00Z",
  },
  {
    id: "mock-2",
    studio_id: "mock-studio",
    legal_first_name: "Marcus",
    legal_last_name: "Webb",
    preferred_name: "Marc",
    date_of_birth: "1992-07-22",
    is_minor: false,
    email: "marcus.webb@email.com",
    phone: "(555) 876-5432",
    status: "active",
    membership_start_date: "2022-01-15",
    tags: ["adult", "competitor"],
    guardians: [],
    created_at: "2022-01-15T00:00:00Z",
    updated_at: "2024-10-20T00:00:00Z",
  },
  {
    id: "mock-3",
    studio_id: "mock-studio",
    legal_first_name: "Sofia",
    legal_last_name: "Reyes",
    preferred_name: undefined,
    date_of_birth: "2012-11-30",
    is_minor: true,
    email: undefined,
    phone: undefined,
    status: "trialing",
    membership_start_date: "2024-12-01",
    tags: ["youth", "trial"],
    guardians: [
      {
        id: "g-2",
        first_name: "Carmen",
        last_name: "Reyes",
        email: "carmen.reyes@email.com",
        phone: "(555) 345-6789",
        relation: "Mother",
        is_primary_contact: true,
      },
    ],
    created_at: "2024-12-01T00:00:00Z",
    updated_at: "2024-12-01T00:00:00Z",
  },
  {
    id: "mock-4",
    studio_id: "mock-studio",
    legal_first_name: "Derek",
    legal_last_name: "Kim",
    preferred_name: "Derek",
    date_of_birth: "1988-04-05",
    is_minor: false,
    email: "derek.kim@email.com",
    phone: "(555) 456-7890",
    status: "inactive",
    membership_start_date: "2021-06-01",
    tags: ["adult"],
    guardians: [],
    created_at: "2021-06-01T00:00:00Z",
    updated_at: "2024-08-10T00:00:00Z",
  },
  {
    id: "mock-5",
    studio_id: "mock-studio",
    legal_first_name: "Priya",
    legal_last_name: "Sharma",
    preferred_name: "Priya",
    date_of_birth: "2010-09-18",
    is_minor: true,
    email: undefined,
    phone: undefined,
    status: "active",
    membership_start_date: "2023-03-10",
    tags: ["youth"],
    guardians: [
      {
        id: "g-3",
        first_name: "Raj",
        last_name: "Sharma",
        email: "raj.sharma@email.com",
        phone: "(555) 567-8901",
        relation: "Father",
        is_primary_contact: true,
      },
    ],
    created_at: "2023-03-10T00:00:00Z",
    updated_at: "2024-11-01T00:00:00Z",
  },
  {
    id: "mock-6",
    studio_id: "mock-studio",
    legal_first_name: "James",
    legal_last_name: "O'Brien",
    preferred_name: "Jimmy",
    date_of_birth: "1979-12-01",
    is_minor: false,
    email: "james.obrien@email.com",
    phone: "(555) 678-9012",
    status: "paused",
    membership_start_date: "2020-08-20",
    notes: "On medical hold until Feb 2025. Contact before reactivating.",
    tags: ["adult", "medical-hold"],
    guardians: [],
    created_at: "2020-08-20T00:00:00Z",
    updated_at: "2024-12-05T00:00:00Z",
  },
];

export const MOCK_STUDENT_LIST: StudentListResponse = {
  items: MOCK_STUDENTS,
  total: MOCK_STUDENTS.length,
  page: 1,
  page_size: 50,
};

// ---- Phase 3: Schedule Mock Data ----

import type {
  ClassTemplate,
  ClassSession,
  AttendanceRecord,
  BeltLadder,
  BeltRank,
  EligibilityEntry,
  Lead,
} from "@/types";

function todayStr(): string {
  return new Date().toISOString().split("T")[0];
}

function dayOfWeek(): number {
  return new Date().getDay(); // 0=Sunday
}

export const MOCK_CLASS_TEMPLATES: ClassTemplate[] = [
  {
    id: "tmpl-1",
    studio_id: "mock-studio",
    name: "Kids BJJ Fundamentals",
    day_of_week: dayOfWeek(),
    start_date: todayStr(),
    start_time: "16:00",
    end_time: "16:45",
    capacity: 20,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "tmpl-2",
    studio_id: "mock-studio",
    name: "Adult No-Gi",
    day_of_week: dayOfWeek(),
    start_date: todayStr(),
    start_time: "18:00",
    end_time: "19:30",
    capacity: 30,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "tmpl-3",
    studio_id: "mock-studio",
    name: "Open Mat",
    day_of_week: (dayOfWeek() + 1) % 7,
    start_date: todayStr(),
    start_time: "10:00",
    end_time: "12:00",
    capacity: 40,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "tmpl-4",
    studio_id: "mock-studio",
    name: "Competition Prep",
    day_of_week: (dayOfWeek() + 2) % 7,
    start_date: todayStr(),
    start_time: "17:00",
    end_time: "18:30",
    capacity: 15,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
];

export const MOCK_SESSIONS: ClassSession[] = [
  {
    id: "sess-1",
    studio_id: "mock-studio",
    template_id: "tmpl-1",
    name: "Kids BJJ Fundamentals",
    date: todayStr(),
    start_time: "16:00",
    end_time: "16:45",
    capacity: 20,
    status: "scheduled",
    created_at: todayStr() + "T00:00:00Z",
    attendance_count: 3,
  },
  {
    id: "sess-2",
    studio_id: "mock-studio",
    template_id: "tmpl-2",
    name: "Adult No-Gi",
    date: todayStr(),
    start_time: "18:00",
    end_time: "19:30",
    capacity: 30,
    status: "scheduled",
    created_at: todayStr() + "T00:00:00Z",
    attendance_count: 2,
  },
];

export const MOCK_ATTENDANCE: AttendanceRecord[] = [
  {
    id: "att-1",
    studio_id: "mock-studio",
    session_id: "sess-1",
    student_id: "mock-1",
    status: "present",
    checked_in_at: todayStr() + "T16:00:00Z",
    student_name: "Aiko Tanaka",
  },
  {
    id: "att-2",
    studio_id: "mock-studio",
    session_id: "sess-1",
    student_id: "mock-5",
    status: "present",
    checked_in_at: todayStr() + "T16:02:00Z",
    student_name: "Priya Sharma",
  },
  {
    id: "att-3",
    studio_id: "mock-studio",
    session_id: "sess-1",
    student_id: "mock-3",
    status: "late",
    checked_in_at: todayStr() + "T16:10:00Z",
    student_name: "Sofia Reyes",
  },
];

// ---- Phase 4: Belt Tracker Mock Data ----

export const MOCK_BELT_RANKS: BeltRank[] = [
  // ---- White Belt ----
  {
    id: "rank-1",
    ladder_id: "ladder-1",
    studio_id: "mock-studio",
    name: "White Belt",
    color_hex: "#FFFFFF",
    display_order: 0,
    min_classes: 0,
    min_months: 0,
    requires_approval: false,
    is_tip: false,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "rank-1a",
    ladder_id: "ladder-1",
    studio_id: "mock-studio",
    name: "Red Tip 1",
    color_hex: "#FFFFFF",
    tip_color_hex: "#EF4444",
    display_order: 1,
    min_classes: 8,
    min_months: 1,
    requires_approval: false,
    is_tip: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "rank-1b",
    ladder_id: "ladder-1",
    studio_id: "mock-studio",
    name: "Red Tip 2",
    color_hex: "#FFFFFF",
    tip_color_hex: "#EF4444",
    display_order: 2,
    min_classes: 8,
    min_months: 1,
    requires_approval: false,
    is_tip: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "rank-1c",
    ladder_id: "ladder-1",
    studio_id: "mock-studio",
    name: "Red Tip 3",
    color_hex: "#FFFFFF",
    tip_color_hex: "#EF4444",
    display_order: 3,
    min_classes: 8,
    min_months: 1,
    requires_approval: false,
    is_tip: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "rank-1d",
    ladder_id: "ladder-1",
    studio_id: "mock-studio",
    name: "Black Tip",
    color_hex: "#FFFFFF",
    tip_color_hex: "#111111",
    display_order: 4,
    min_classes: 10,
    min_months: 2,
    requires_approval: true,
    is_tip: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  // ---- Yellow Belt ----
  {
    id: "rank-2",
    ladder_id: "ladder-1",
    studio_id: "mock-studio",
    name: "Yellow Belt",
    color_hex: "#EAB308",
    display_order: 5,
    min_classes: 20,
    min_months: 3,
    requires_approval: true,
    is_tip: false,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "rank-2a",
    ladder_id: "ladder-1",
    studio_id: "mock-studio",
    name: "Yellow Tip",
    color_hex: "#EAB308",
    tip_color_hex: "#EAB308",
    display_order: 6,
    min_classes: 10,
    min_months: 2,
    requires_approval: false,
    is_tip: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  // ---- Orange Belt ----
  {
    id: "rank-3",
    ladder_id: "ladder-1",
    studio_id: "mock-studio",
    name: "Orange Belt",
    color_hex: "#F97316",
    display_order: 7,
    min_classes: 30,
    min_months: 6,
    requires_approval: true,
    is_tip: false,
    created_at: "2024-01-01T00:00:00Z",
  },
  // ---- Purple Belt ----
  {
    id: "rank-4",
    ladder_id: "ladder-1",
    studio_id: "mock-studio",
    name: "Purple Belt",
    color_hex: "#8B5CF6",
    display_order: 8,
    min_classes: 50,
    min_months: 12,
    requires_approval: true,
    is_tip: false,
    created_at: "2024-01-01T00:00:00Z",
  },
  // ---- Blue Belt ----
  {
    id: "rank-5",
    ladder_id: "ladder-1",
    studio_id: "mock-studio",
    name: "Blue Belt",
    color_hex: "#3B82F6",
    display_order: 9,
    min_classes: 75,
    min_months: 18,
    requires_approval: true,
    is_tip: false,
    created_at: "2024-01-01T00:00:00Z",
  },
  // ---- Green Belt ----
  {
    id: "rank-6",
    ladder_id: "ladder-1",
    studio_id: "mock-studio",
    name: "Green Belt",
    color_hex: "#22C55E",
    display_order: 10,
    min_classes: 100,
    min_months: 24,
    requires_approval: true,
    is_tip: false,
    created_at: "2024-01-01T00:00:00Z",
  },
  // ---- Brown Belt ----
  {
    id: "rank-7",
    ladder_id: "ladder-1",
    studio_id: "mock-studio",
    name: "Brown Belt",
    color_hex: "#92400E",
    display_order: 11,
    min_classes: 150,
    min_months: 36,
    requires_approval: true,
    is_tip: false,
    created_at: "2024-01-01T00:00:00Z",
  },
  // ---- Black Belt ----
  {
    id: "rank-8",
    ladder_id: "ladder-1",
    studio_id: "mock-studio",
    name: "Black Belt",
    color_hex: "#111111",
    display_order: 12,
    min_classes: 250,
    min_months: 60,
    requires_approval: true,
    is_tip: false,
    created_at: "2024-01-01T00:00:00Z",
  },
];

export const MOCK_BELT_LADDER: BeltLadder = {
  id: "ladder-1",
  studio_id: "mock-studio",
  name: "Kids Martial Arts",
  sub_rank_term: "Stripe",
  created_at: "2024-01-01T00:00:00Z",
  updated_at: "2024-01-01T00:00:00Z",
  ranks: MOCK_BELT_RANKS,
};

export const MOCK_ELIGIBILITY: EligibilityEntry[] = [
  {
    student_id: "mock-1",
    student_name: "Aiko Tanaka",
    current_rank_name: "White Belt",
    current_rank_color: "#FFFFFF",
    next_rank_name: "Red Tip 1",
    next_rank_color: "#FFFFFF",
    classes_since_promo: 6,
    classes_required: 8,
    days_at_rank: 25,
    days_required: 30,
    classes_met: false,
    time_met: false,
    needs_approval: false,
    is_eligible: false,
  },
  {
    student_id: "mock-5",
    student_name: "Priya Sharma",
    current_rank_name: "Red Tip 2",
    current_rank_color: "#FFFFFF",
    next_rank_name: "Red Tip 3",
    next_rank_color: "#FFFFFF",
    classes_since_promo: 9,
    classes_required: 8,
    days_at_rank: 35,
    days_required: 30,
    classes_met: true,
    time_met: true,
    needs_approval: false,
    is_eligible: true,
  },
  {
    student_id: "mock-2",
    student_name: "Marc Webb",
    current_rank_name: "Black Tip",
    current_rank_color: "#FFFFFF",
    next_rank_name: "Yellow Belt",
    next_rank_color: "#EAB308",
    classes_since_promo: 12,
    classes_required: 10,
    days_at_rank: 65,
    days_required: 60,
    classes_met: true,
    time_met: true,
    needs_approval: true,
    is_eligible: false,
  },
  {
    student_id: "mock-6",
    student_name: "Jimmy O'Brien",
    current_rank_name: "Blue Belt",
    current_rank_color: "#3B82F6",
    next_rank_name: "Green Belt",
    next_rank_color: "#22C55E",
    classes_since_promo: 110,
    classes_required: 100,
    days_at_rank: 560,
    days_required: 548,
    classes_met: true,
    time_met: true,
    needs_approval: true,
    is_eligible: false,
  },
  {
    student_id: "mock-4",
    student_name: "Derek Kim",
    current_rank_name: "Yellow Belt",
    current_rank_color: "#EAB308",
    next_rank_name: "Orange Belt",
    next_rank_color: "#F97316",
    classes_since_promo: 22,
    classes_required: 30,
    days_at_rank: 120,
    days_required: 180,
    classes_met: false,
    time_met: false,
    needs_approval: true,
    is_eligible: false,
  },
];

// ---- Phase 5: Leads Mock Data ----


export const MOCK_LEADS: Lead[] = [
  {
    id: "lead-1",
    studio_id: "mock-studio",
    first_name: "David",
    last_name: "Chen",
    email: "david.chen@email.com",
    phone: "(555) 111-2222",
    source: "website",
    stage: "inquiry",
    program_interest: "Adult BJJ",
    is_minor: false,
    notes: "Interested in evening classes. Has prior wrestling experience.",
    created_at: "2025-04-15T10:00:00Z",
    updated_at: "2025-04-15T10:00:00Z",
  },
  {
    id: "lead-2",
    studio_id: "mock-studio",
    first_name: "Maria",
    last_name: "Gonzalez",
    email: "maria.g@email.com",
    phone: "(555) 333-4444",
    source: "referral",
    stage: "trial_scheduled",
    program_interest: "Kids Martial Arts",
    is_minor: true,
    guardian_name: "Elena Gonzalez",
    guardian_email: "elena.g@email.com",
    guardian_phone: "(555) 333-4445",
    follow_up_date: "2025-04-20",
    notes: "Referred by Carmen Reyes. Daughter is 8 years old.",
    created_at: "2025-04-14T14:00:00Z",
    updated_at: "2025-04-16T09:00:00Z",
  },
  {
    id: "lead-3",
    studio_id: "mock-studio",
    first_name: "Tyler",
    last_name: "Brooks",
    email: "tyler.b@email.com",
    source: "social",
    stage: "trial_completed",
    program_interest: "Adult No-Gi",
    is_minor: false,
    notes: "Completed trial class on 4/12. Very enthusiastic. Follow up with pricing.",
    created_at: "2025-04-10T08:00:00Z",
    updated_at: "2025-04-13T11:00:00Z",
  },
  {
    id: "lead-4",
    studio_id: "mock-studio",
    first_name: "Sarah",
    last_name: "Kim",
    email: "sarah.kim@email.com",
    phone: "(555) 555-6666",
    source: "walk_in",
    stage: "offer_sent",
    program_interest: "Adult BJJ",
    is_minor: false,
    follow_up_date: "2025-04-18",
    notes: "Sent Growth plan pricing. Waiting for decision.",
    created_at: "2025-04-08T16:00:00Z",
    updated_at: "2025-04-15T10:00:00Z",
  },
  {
    id: "lead-5",
    studio_id: "mock-studio",
    first_name: "Ryan",
    last_name: "Patel",
    email: "ryan.p@email.com",
    phone: "(555) 777-8888",
    source: "search",
    stage: "closed_lost",
    program_interest: "Competition",
    is_minor: false,
    lost_reason: "price_objection",
    notes: "Price was the deciding factor. May reconsider if we run a promo.",
    created_at: "2025-04-01T12:00:00Z",
    updated_at: "2025-04-10T15:00:00Z",
  },
];
