import type { BeltLadder, BeltRank, Program, StaffMember } from "@/types";
import { MOCK_BELT_LADDER } from "@/lib/mock-data";

export const DEMO_STUDIO_NAME = "River City Martial Arts";

export const MOCK_PROGRAMS: Program[] = [
  {
    id: "program-bjj-core",
    studio_id: "mock-studio",
    name: "Brazilian Jiu-Jitsu Core",
    description: "Shared rank plan for kids, adults, fundamentals, and no-gi.",
    color_hex: "#38BDF8",
    sort_order: 10,
    is_system: false,
    archived_at: null,
    created_at: "2026-04-21T09:00:00Z",
    updated_at: "2026-04-21T09:00:00Z",
    usage: { student_count: 18, active_student_count: 17, class_count: 4, active_class_count: 4, lead_count: 5, belt_ladder_count: 1 },
  },
  {
    id: "program-tae-kwon-do",
    studio_id: "mock-studio",
    name: "Tae Kwon Do Fundamentals",
    description: "Foundational forms, footwork, sparring, and confidence.",
    color_hex: "#F59E0B",
    sort_order: 20,
    is_system: false,
    archived_at: null,
    created_at: "2026-04-21T09:00:00Z",
    updated_at: "2026-04-21T09:00:00Z",
    usage: { student_count: 4, active_student_count: 4, class_count: 1, active_class_count: 1, lead_count: 1, belt_ladder_count: 1 },
  },
  {
    id: "program-unassigned",
    studio_id: "mock-studio",
    name: "Unassigned",
    description: "Students awaiting program assignment.",
    color_hex: "#94A3B8",
    sort_order: 9999,
    is_system: true,
    archived_at: null,
    created_at: "2026-04-21T09:00:00Z",
    updated_at: "2026-04-21T09:00:00Z",
    usage: { student_count: 0, active_student_count: 0, class_count: 0, active_class_count: 0, lead_count: 0, belt_ladder_count: 0 },
  },
];

const MOCK_TAE_KWON_DO_RANKS: BeltRank[] = [
  {
    id: "tkd-rank-1",
    ladder_id: "ladder-tae-kwon-do",
    studio_id: "mock-studio",
    name: "White Belt",
    color_hex: "#FFFFFF",
    display_order: 0,
    min_classes: 0,
    min_months: 0,
    requires_approval: false,
    is_tip: false,
    created_at: "2026-04-21T09:00:00Z",
  },
  {
    id: "tkd-rank-1a",
    ladder_id: "ladder-tae-kwon-do",
    studio_id: "mock-studio",
    name: "Yellow Stripe",
    color_hex: "#FFFFFF",
    tip_color_hex: "#EAB308",
    display_order: 1,
    min_classes: 5,
    min_months: 1,
    requires_approval: false,
    is_tip: true,
    created_at: "2026-04-21T09:00:00Z",
  },
  {
    id: "tkd-rank-2",
    ladder_id: "ladder-tae-kwon-do",
    studio_id: "mock-studio",
    name: "Yellow Belt",
    color_hex: "#EAB308",
    display_order: 2,
    min_classes: 10,
    min_months: 2,
    requires_approval: true,
    is_tip: false,
    created_at: "2026-04-21T09:00:00Z",
  },
  {
    id: "tkd-rank-2a",
    ladder_id: "ladder-tae-kwon-do",
    studio_id: "mock-studio",
    name: "Green Stripe",
    color_hex: "#FFFFFF",
    tip_color_hex: "#22C55E",
    display_order: 3,
    min_classes: 14,
    min_months: 3,
    requires_approval: false,
    is_tip: true,
    created_at: "2026-04-21T09:00:00Z",
  },
  {
    id: "tkd-rank-3",
    ladder_id: "ladder-tae-kwon-do",
    studio_id: "mock-studio",
    name: "Green Belt",
    color_hex: "#22C55E",
    display_order: 4,
    min_classes: 18,
    min_months: 4,
    requires_approval: true,
    is_tip: false,
    created_at: "2026-04-21T09:00:00Z",
  },
  {
    id: "tkd-rank-3a",
    ladder_id: "ladder-tae-kwon-do",
    studio_id: "mock-studio",
    name: "Blue Stripe",
    color_hex: "#FFFFFF",
    tip_color_hex: "#3B82F6",
    display_order: 5,
    min_classes: 22,
    min_months: 5,
    requires_approval: false,
    is_tip: true,
    created_at: "2026-04-21T09:00:00Z",
  },
  {
    id: "tkd-rank-4",
    ladder_id: "ladder-tae-kwon-do",
    studio_id: "mock-studio",
    name: "Blue Belt",
    color_hex: "#3B82F6",
    display_order: 6,
    min_classes: 28,
    min_months: 6,
    requires_approval: true,
    is_tip: false,
    created_at: "2026-04-21T09:00:00Z",
  },
];

const MOCK_TAE_KWON_DO_LADDER: BeltLadder = {
  id: "ladder-tae-kwon-do",
  studio_id: "mock-studio",
  name: "Tae Kwon Do Fundamentals",
  program_id: "program-tae-kwon-do",
  sub_rank_term: "Stripe",
  created_at: "2026-04-21T09:00:00Z",
  updated_at: "2026-04-21T09:00:00Z",
  ranks: MOCK_TAE_KWON_DO_RANKS,
};

export const MOCK_BELT_LADDERS: BeltLadder[] = [MOCK_BELT_LADDER, MOCK_TAE_KWON_DO_LADDER];

export const MOCK_STAFF_MEMBERS: StaffMember[] = [
  {
    id: "preview-staff-admin",
    studio_id: "mock-studio",
    user_id: "preview-user",
    email: "demo@koaryu.local",
    full_name: "Demo User",
    role: "admin",
    status: "active",
    invited_by: null,
    created_at: "2026-04-21T09:00:00Z",
    updated_at: "2026-04-21T09:00:00Z",
    last_sign_in_at: "2026-04-24T21:00:00Z",
  },
  {
    id: "preview-staff-instructor",
    studio_id: "mock-studio",
    user_id: "preview-instructor",
    email: "sensei@rivercity.example",
    full_name: "Maya Chen",
    role: "instructor",
    status: "active",
    invited_by: "preview-user",
    created_at: "2026-04-22T15:30:00Z",
    updated_at: "2026-04-22T15:30:00Z",
    last_sign_in_at: "2026-04-24T18:15:00Z",
  },
  {
    id: "preview-staff-front-desk",
    studio_id: "mock-studio",
    user_id: "preview-front-desk",
    email: "frontdesk@rivercity.example",
    full_name: "Jordan Lee",
    role: "front_desk",
    status: "pending",
    invited_by: "preview-user",
    created_at: "2026-04-23T11:45:00Z",
    updated_at: "2026-04-23T11:45:00Z",
    last_sign_in_at: null,
  },
];
